const fs=require('node:fs'), assert=require('node:assert/strict'), ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');
function load(path,mocks={}){const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const exp={};new Function('require','exports',code)(id=>mocks[id]??require(id),exp);return exp}
const assets=load('packages/mochi-assets/index.js');
const mochi=load('lib/mochi.ts',{'../packages/mochi-assets/index.js':assets});
const {walkingRecords,previousWalking,walkingDraft,walkingTimerMinutes}=load('lib/walking.ts',{'./mochi':mochi});
const entry=(day,walkingMinutes)=>({day,walkingMinutes,weight:60,mood:0,done:['h0'],note:'保存したメモ'});
const records=[entry('2026-10-01',35),entry('2026-09-29',0),entry('2026-09-30',null),entry('2026-09-27',20),entry('2026-10-02',40),entry('2026-08-31',15),entry('2026-09-28',undefined)];
assert.deepEqual(walkingRecords(records,'2026-10-01').map(e=>[e.day,e.walkingMinutes]),[['2026-09-27',20],['2026-09-29',0],['2026-10-01',35]]);
assert.deepEqual(walkingRecords(records,'2026-10-01',2).map(e=>e.walkingMinutes),[35]);
assert.equal(previousWalking(records,'2026-10-01').walkingMinutes,0);
assert.equal(previousWalking(records,'2026-09-27').walkingMinutes,15);
assert.equal(previousWalking(records,'2026-08-31'),undefined);
assert.deepEqual(walkingRecords([entry('2026-10-01',2.5),entry('2026-10-01',-1),entry('2026-10-01',1441)],'2026-10-01'),[]);
assert.deepEqual(walkingRecords([],'2026-10-01'),[]);
assert.equal(records[0].day,'2026-10-01');
// Default to the closest earlier measurement without treating it as today's record.
const blank=entry('2026-10-01',null);
assert.deepEqual(walkingDraft(records,blank),{value:'0',included:false});
assert.deepEqual(walkingDraft(records,blank,true),{value:'0',included:true});
assert.deepEqual(walkingDraft(records,entry('2026-10-03',null)),{value:'40',included:false});
assert.deepEqual(walkingDraft(records,entry('2026-10-03',null),true),{value:'0',included:true});
assert.deepEqual(walkingDraft(records,entry('2026-10-02',12),true),{value:'12',included:true});
assert.deepEqual(walkingDraft(records,entry('2026-10-02',0),true),{value:'0',included:true});
assert.deepEqual(walkingDraft([entry('2026-10-02',40)],blank),{value:'0',included:false});
assert.deepEqual(walkingDraft([],blank),{value:'0',included:false});
assert.equal(walkingTimerMinutes(0),0);
assert.equal(walkingTimerMinutes(1),1);
assert.equal(walkingTimerMinutes(59),1);
assert.equal(walkingTimerMinutes(60),1);
assert.equal(walkingTimerMinutes(61),2);
assert.equal(walkingTimerMinutes(86400),1440);
assert.equal(mochi.normalizeSettings(null).walkingGoalMinutes,null);
assert.equal(mochi.normalizeSettings({walkingGoalMinutes:12}).walkingGoalMinutes,12);
for(const walkingGoalMinutes of [0,1441,2.5,'10',undefined])assert.equal(mochi.normalizeSettings({walkingGoalMinutes}).walkingGoalMinutes,null);
assert.equal(blank.walkingMinutes,null);
// Adding walking minutes keeps older rows intact and initially unrecorded.
const db=new DatabaseSync(':memory:');
const migrations=fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort();
for(const file of migrations.filter(f=>!f.startsWith('0002_')))db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
db.prepare('INSERT INTO entries(user_id,day,weight,mood,done,note) VALUES(?,?,?,?,?,?)').run('old-user','2026-09-29',60,0,'["h0"]','保存したメモ');
db.exec(fs.readFileSync('drizzle/0002_walking_minutes.sql','utf8'));
assert.deepEqual({...db.prepare('SELECT weight,mood,done,note,walking_minutes FROM entries').get()},{weight:60,mood:0,done:'["h0"]',note:'保存したメモ',walking_minutes:null});
db.close();
console.log('PASS: walking chronology, previous-minute defaults, zero versus skipped days, historical comparisons, date windows, invalid durations and migration preservation.');
