const fs = require('node:fs'), assert = require('node:assert/strict'), ts = require('typescript');
const code = ts.transpileModule(fs.readFileSync('lib/weight.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const helpers = {};
new Function('exports', code)(helpers);
const { latestWeight, previousWeight, weightDraft, adjustWeight, weightChange } = helpers;
const entry = (day, weight) => ({ day, weight, mood: null, done: [], note: '' });
const records = [entry('2026-09-27', 62), entry('2026-10-01', 61.3), entry('2026-09-30', null), entry('2026-09-29', 61.5), entry('2026-09-28', null)];
assert.equal(latestWeight(records, '2026-10-02').weight, 61.3);
assert.equal(previousWeight(records, '2026-10-01').weight, 61.5);
assert.equal(previousWeight(records, '2026-09-29').weight, 62);
assert.equal(previousWeight(records, '2026-09-27'), undefined);
assert.equal(latestWeight([], '2026-10-01'), undefined);
assert.deepEqual(weightDraft(records, entry('2026-10-02', null)), { value: '61.3', included: false });
assert.deepEqual(weightDraft(records, entry('2026-10-02', null), true), { value: '61.3', included: true });
assert.deepEqual(weightDraft(records, entry('2026-09-29', 61.55)), { value: '61.55', included: true });
assert.equal(weightDraft(records, entry('2026-09-26', null)).included, false);
let weight = 60;
for (let index = 0; index < 10; index++) weight = adjustWeight(weight, 1);
assert.equal(weight, 61);
for (let index = 0; index < 10; index++) weight = adjustWeight(weight, -1);
assert.equal(weight, 60);
assert.equal(adjustWeight(1, -10), 1);
assert.equal(adjustWeight(500, 10), 500);
assert.equal(weightChange(60.1, 60), '前回から +0.1 kg');
assert.equal(weightChange(59.9, 60), '前回から −0.1 kg');
assert.equal(weightChange(60, 60), '前回と同じ');
console.log('PASS: dated weight history, skipped days, historical edits, optional carry-forward, existing precision, decimal increments, bounds and changes.');
