'use client';
import { useEffect, useRef, useState } from 'react';
import { Hand, Leaf, Heart, Play, Pause, Square, Music, Volume2, VolumeX, Eye, Sprout, BookOpen, Armchair, Moon, Grid2X2, House } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Pet } from './pet';
import { MochiSound } from '@/lib/mochi-sound';
import { groundingPrompts } from '@/lib/companion-content';
import type { CompanionPreferences, Interaction } from '@/lib/companion';
import type { Species, Outfit } from '@/lib/mochi';

import { readTimer, timerElapsed as elapsed, pausedTimer, type TimerData } from '@/lib/activity-timer';
export function ActivityTimer({scope,onWalking,onStretch}:{scope:string;onWalking:(minutes:number)=>void;onStretch:()=>void}){
 const key='mochi-days:timer:v1:'+encodeURIComponent(scope);
 const [data,setData]=useState<TimerData>(()=>{try{return readTimer(localStorage.getItem(key))}catch{}return {kind:'walk',seconds:0,started:null}});
 const [tick,setTick]=useState(0),[ready,setReady]=useState(false);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(data))}catch{}},[key,data]);
 useEffect(()=>{if(data.started===null)return;const timer=setInterval(()=>setTick(n=>n+1),1000);return()=>clearInterval(timer)},[data.started]);
 const seconds=Math.min(86400,Math.floor(elapsed(data))),minutes=Math.floor(seconds/60);
 void tick;
 function finish(){setData(pausedTimer(data));setReady(true);}
 return <section className="comfort-panel activity-timer"><h3>もちと、少しだけ</h3><div className="choice-row"><Button type="button" variant={data.kind==='walk'?'secondary':'outline'} disabled={data.started!==null} aria-pressed={data.kind==='walk'} onClick={()=>setData({kind:'walk',seconds:0,started:null})}>おさんぽ</Button><Button type="button" variant={data.kind==='stretch'?'secondary':'outline'} disabled={data.started!==null} aria-pressed={data.kind==='stretch'} onClick={()=>setData({kind:'stretch',seconds:0,started:null})}>ストレッチ</Button></div><p className="timer-clock" role="timer" aria-label="経過時間">{String(minutes).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</p><p>途中で休んでも大丈夫。記録は、終わってから選べるよ。</p><div className="choice-row"><Button type="button" variant="outline" onClick={()=>{setReady(false);setData(data.started===null?{...data,started:Date.now()}:{...data,seconds:elapsed(data),started:null})}}>{data.started===null?<Play size={16}/>:<Pause size={16}/>} {data.started===null?'はじめる・再開':'ひと休み'}</Button><Button type="button" variant="outline" onClick={finish}><Square size={15}/>おしまい</Button></div>{ready&&<div className="gentle-result"><p>一緒に過ごせたね。残すかどうかも、自分のペースで。</p><Button type="button" onClick={()=>{const reset={...data,seconds:0,started:null};setData(reset);try{localStorage.setItem(key,JSON.stringify(reset))}catch{}setReady(false);data.kind==='walk'?onWalking(Math.min(1440,minutes)):onStretch()}}>{data.kind==='walk'?`${minutes}分を確かめて記録する`:'少しできた習慣を選ぶ'}</Button><Button type="button" variant="ghost" onClick={()=>{setData({...data,seconds:0,started:null});setReady(false)}}>時間をリセット</Button></div>}</section>;
}
export function ComfortActivities({species,outfit,preferences,onPreference,onInteract}:{species:Species;outfit:Outfit;preferences:CompanionPreferences;onPreference:(patch:Partial<CompanionPreferences>)=>Promise<boolean>;onInteract:(kind:Interaction)=>void}){
 const [activity,setActivity]=useState<'breathe'|'ground'|'puzzle'|'hide'|'rhythm'|'garden'>('breathe');
 const [duration,setDuration]=useState(30),[breathing,setBreathing]=useState(false),[seconds,setSeconds]=useState(0),[done,setDone]=useState(false);
 const [ground,setGround]=useState(0),[pieces,setPieces]=useState<number[]>([]),[hiding,setHiding]=useState(1),[searched,setSearched]=useState<number[]>([]),[found,setFound]=useState(false),[rhythm,setRhythm]=useState(0),[leaves,setLeaves]=useState([0,1,2,3]),[rocks,setRocks]=useState([false,false,false]);
 const [playing,setPlaying]=useState(false),[soundError,setSoundError]=useState('');
 const sound=useRef<MochiSound|null>(null),breathStart=useRef(0);
 function audio(){return sound.current??(sound.current=new MochiSound())}
 useEffect(()=>()=>sound.current?.destroy(),[]);
 useEffect(()=>{const quiet=()=>{if(document.hidden){sound.current?.stop();setPlaying(false);setBreathing(false)}};document.addEventListener('visibilitychange',quiet);return()=>document.removeEventListener('visibilitychange',quiet)},[]);
 useEffect(()=>{
  if(!breathing)return;
  const timer=setInterval(()=>{const passed=Math.floor((Date.now()-breathStart.current)/1000);setSeconds(Math.min(duration,passed));if(passed>=duration){setBreathing(false);setDone(true);onInteract('breathing')}},250);
  return()=>clearInterval(timer);
 },[breathing,duration,onInteract]);
 async function play(patch:Partial<CompanionPreferences>={}){try{const prefs={...preferences,...patch};setSoundError('');await audio().start(prefs.ambient,prefs.music,prefs.volume,prefs.melody);setPlaying(prefs.ambient!=='off'||prefs.music)}catch(error){setPlaying(false);setSoundError(error instanceof Error?error.message:'音を再生できませんでした。')}}
 function changeSound(patch:Partial<CompanionPreferences>){if(playing)void play(patch);void onPreference(patch);}
 const playPanel=useRef<HTMLElement|null>(null);
 function chooseActivity(next:typeof activity){setActivity(next);setBreathing(false);setDone(false);requestAnimationFrame(()=>playPanel.current?.scrollIntoView({block:'start',behavior:'auto'}));}
 return <div className="comfort-activities">
  <section className="comfort-panel play-panel" ref={playPanel}>
   {activity==='breathe'&&<><h3>もちと、ひと呼吸</h3><p>いつもの呼吸で大丈夫。動きを眺めるだけでも。</p><div className="choice-row">{[30,60].map(value=><Button type="button" key={value} disabled={breathing} variant={duration===value?'secondary':'outline'} aria-pressed={duration===value} onClick={()=>{setDuration(value);setSeconds(0);setDone(false)}}>{value}秒</Button>)}</div><div className={'breathing-pet '+(breathing?'breathing-now':'')}><Pet species={species} outfit={outfit} pose={done?1:2}/><span className="breath-halo"/></div><p aria-live="polite">{done?'ひと息つけたね。おつかれさま。':breathing?'ゆっくり、きみの呼吸で。': '気が向いたら、一緒に。'} {breathing&&`${seconds} / ${duration}秒`}</p><Button type="button" variant="outline" onClick={()=>{if(breathing){setBreathing(false);setDone(false)}else{breathStart.current=Date.now();setSeconds(0);setDone(false);setBreathing(true)}}}>{breathing?'ここでおしまい':'一緒にひと呼吸'}</Button></>}
   {activity==='ground'&&<><h3>今ここを、ひとつ見つける</h3><Eye size={32}/><p className="grounding-prompt">{groundingPrompts[ground]}</p><p>答えを書かなくても大丈夫。気づいたら、そっとひと息。</p><Button type="button" variant="outline" onClick={()=>setGround((ground+1)%groundingPrompts.length)}>ほかのきっかけ</Button></>}
   {activity==='puzzle'&&<><h3>もちの、ゆっくり絵合わせ</h3><p>好きなピースを開いてみてね。速さも点数もないよ。</p><div className="pet-puzzle">{Array.from({length:9},(_,index)=><button key={index} type="button" aria-label={`絵合わせのピース${index+1}`} aria-pressed={pieces.includes(index)} onClick={()=>{if(pieces.includes(index))return;const next=[...pieces,index];setPieces(next);if(next.length===9)onInteract('puzzle')}}>{pieces.includes(index)?<span className="puzzle-tile-art" style={{left:-(index%3)*100+'%',top:-Math.floor(index/3)*100+'%'}}><Pet species={species} outfit={outfit} pose={0}/></span>:<Heart size={24}/>}</button>)}</div>{pieces.length===9&&<p aria-live="polite">見つけてくれて、うれしいな。</p>}<Button type="button" variant="ghost" onClick={()=>setPieces([])}>もう一度、ゆっくり</Button></>}
   {activity==='hide'&&<><h3>もちの、かくれんぼ</h3><p>{found?'ここにいたよ。見つけてくれて、うれしいな。':searched.length?'小さなおててが、ちらっと見えたかも。':'気になるところを、のぞいてみよう。'}</p><div className="hide-spots">{[BookOpen,Armchair,Sprout].map((Icon,index)=><button key={index} type="button" aria-label={['絵本のうしろ','クッションのうしろ','鉢のうしろ'][index]} onClick={()=>{if(found)return;const next=[...new Set([...searched,index])];setSearched(next);if(index===hiding||next.length===3){setFound(true);onInteract('hide')}}}>{found&&index===hiding?<Pet species={species} outfit={outfit} pose={1} small/>:<Icon size={42}/>}<span>{searched.includes(index)&&!found?'ちらっ': ['絵本','クッション','鉢'][index]}</span></button>)}</div><Button type="button" variant="ghost" onClick={()=>{setHiding((hiding+1)%3);setSearched([]);setFound(false)}}>もう一度、探そう</Button></>}
   {activity==='rhythm'&&<><h3>ゆっくり、おててを合わせる</h3><div className="rhythm-pet"><Pet species={species} outfit={outfit} pose={rhythm>=4?1:0}/></div><p>タイミングは自由。もちのおててに、そっと。</p><button type="button" className="rhythm-hand" aria-label="もちとおててを合わせる" onClick={()=>{if(rhythm>=4){setRhythm(1);return}const next=rhythm+1;setRhythm(next);if(next===4)onInteract('rhythm')}}><Hand size={35}/></button><div className="rhythm-dots" aria-label={`${Math.min(4,rhythm)}回おててを合わせた`}>{[0,1,2,3].map(index=><Heart key={index} size={16} fill={index<rhythm?'currentColor':'none'}/>)}</div>{rhythm>=4&&<p aria-live="polite">きみのペースで、いっしょにできたね。</p>}</>}
   {activity==='garden'&&<><h3>小さな庭を、のんびり</h3><p>葉っぱを寄せたり、石を並べたり。好きなところまで。</p><div className="little-garden"><div className="garden-leaves">{leaves.map(index=><button key={index} type="button" aria-label={`落ち葉${index+1}を寄せる`} style={{transform:`rotate(${index*37-30}deg)`}} onClick={()=>{setLeaves(leaves.filter(value=>value!==index));onInteract('garden')}}><Leaf size={31}/></button>)}</div><div className="garden-stones">{rocks.map((moved,index)=><button key={index} type="button" aria-label={`小石${index+1}を並べる`} aria-pressed={moved} className={moved?'stone-arranged':''} onClick={()=>{setRocks(rocks.map((value,i)=>i===index?!value:value));onInteract('garden')}}/>)}<span className="leaf-pile"><Leaf size={18}/>{4-leaves.length?4-leaves.length+'枚':''}</span></div></div><Button type="button" variant="ghost" onClick={()=>{setLeaves([0,1,2,3]);setRocks([false,false,false])}}>好きな並びを、もう一度</Button></>}
  </section>
  <div className="activity-choices visual-activities" aria-label="ひと休みの遊び">{([['breathe','深呼吸',Moon],['ground','五感でひと休み',Eye],['puzzle','絵合わせ',Grid2X2],['hide','かくれんぼ',House],['rhythm','おててタッチ',Hand],['garden','庭あそび',Sprout]] as const).map(([id,label,Icon])=><button key={id} type="button" aria-pressed={activity===id} onClick={()=>chooseActivity(id)}><span className={'activity-art activity-art-'+id}><Icon size={30}/></span><strong>{label}</strong></button>)}</div>
  <details className="hub-secondary sound-settings"><summary><Volume2 size={18}/>音・声の設定</summary>
  <section className="comfort-panel sound-panel"><h3><Volume2 size={17}/>好きな音を、少しだけ</h3><p>はじめは無音。再生は、ここで選んだときだけ。</p><label>環境音<select aria-label="環境音" value={preferences.ambient} onChange={event=>changeSound({ambient:event.target.value as CompanionPreferences['ambient']})}><option value="off">無音</option><option value="rain">小雨</option><option value="sea">波</option><option value="forest">森</option></select></label><label className="inline-choice"><input type="checkbox" checked={preferences.music} onChange={event=>changeSound({music:event.target.checked})}/><Music size={16}/>静かな音楽</label><label>音量<input aria-label="音量" type="range" min="0" max="0.5" step="0.01" value={preferences.volume} onChange={event=>changeSound({volume:Number(event.target.value)})}/></label><div className="choice-row"><Button type="button" variant="outline" onClick={()=>{if(playing){sound.current?.stop();setPlaying(false)}else void play()}}>{playing?<VolumeX size={15}/>:<Volume2 size={15}/>} {playing?'音を止める':'音を聞く'}</Button><Button type="button" variant="ghost" onClick={()=>void audio().voice(species,preferences.volume).catch(()=>setSoundError('この端末では声を再生できませんでした。'))}>もちの声を聞く</Button></div><label>静かな音楽<select aria-label="もちと聴く音楽" value={preferences.melody} onChange={event=>changeSound({melody:event.target.value as typeof preferences.melody})}><option value="tea">午後のお茶</option><option value="moon">月あかり</option><option value="garden">小さな庭</option></select></label><label className="inline-choice"><input type="checkbox" checked={preferences.voice} onChange={event=>void onPreference({voice:event.target.checked})}/>触れ合いのとき、もちの短い声</label><label className="inline-choice"><input type="checkbox" disabled={typeof navigator.vibrate!=='function'} checked={preferences.haptics} onChange={event=>{if(event.target.checked)navigator.vibrate?.(12);void onPreference({haptics:event.target.checked})}}/>小さな振動 {typeof navigator.vibrate!=='function'&&<small>この端末では非対応</small>}</label>{soundError&&<p role="status">{soundError}</p>}</section>
  </details>
 </div>;
}
