'use client';
import { useEffect, useState } from 'react';
import { BookOpen, Heart, Gift, Flower2, Cake, Leaf, Moon, MessageCircle, Home, Footprints, Sparkles, ChevronLeft, ChevronRight, Star } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Pet } from './pet';
import { PetPlayground } from './pet-playground';
import { ComfortActivities, ActivityTimer } from './comfort-activities';
import { outfits, pets, daysAgo, allRewardsUnlocked, type State, type Species } from '@/lib/mochi';
import { personalities, tones, supports, memoryQuestions, routes, seasonStories, afterStories } from '@/lib/companion-content';
import { bondCount, bondLevel, plantStage, lettersFor, dailyQuestion, goalStep, walkingJourney, type CompanionState, type CompanionAction, type Interaction, type RoomDesign } from '@/lib/companion';

export type HubPage='profile'|'talk'|'journey'|'rest'|'room'|'gifts';
const pages=[['profile','もちのこと',Heart],['talk','お話',MessageCircle],['journey','おさんぽ',Footprints],['rest','ひと休み',Moon],['room','お部屋',Home],['gifts','贈りもの',Gift]] as const;
export function CompanionGateway({onOpen,ready,quiet}:{onOpen:(page:HubPage)=>void;ready:number;quiet:boolean}){
 return <section className="card companion-gateway"><div className="section-heading"><h2>もちとの時間</h2><span className="subtle">好きなときに</span></div><div className="gateway-choices">{pages.map(([id,label,Icon])=><button type="button" key={id} onClick={()=>onOpen(id)}><Icon size={18}/>{label}{id==='gifts'&&ready>0&&<span className="gift-dot" aria-label="受け取れる贈りもの"/>}</button>)}</div>{!quiet&&<p className="support-copy">お話も、遊びも。気になるところから。</p>}</section>;
}
export function CompanionHub({open,onOpenChange,initialPage,state,companion,day,hour,scope,disabled,onCommand,onInteract,onWalking,onStretch,onNote,onSwitch,onBedtime}:{open:boolean;onOpenChange:(open:boolean)=>void;initialPage:HubPage;state:State;companion:CompanionState;day:string;hour:number;scope:string;disabled:boolean;onCommand:(command:CompanionAction)=>Promise<boolean>;onInteract:(kind:Interaction)=>void;onWalking:(minutes:number)=>void;onStretch:()=>void;onNote:()=>void;onSwitch:(species:Species)=>Promise<boolean>;onBedtime:(selfWords:string,tomorrow:string)=>Promise<boolean>}){
 const [page,setPage]=useState<HubPage>(initialPage),[viewSpecies,setViewSpecies]=useState<Species>(state.settings.species),[letter,setLetter]=useState<{title:string;text:string}|null>(null),[archive,setArchive]=useState(false),[selectedEpisode,setSelectedEpisode]=useState<string|null>(null),[openedGift,setOpenedGift]=useState<string|null>(null);
 const [room,setRoom]=useState<RoomDesign>(companion.preferences.room),[roomDirty,setRoomDirty]=useState(false),[favoriteName,setFavoriteName]=useState(''),[roomAction,setRoomAction]=useState('');
 const [selfWords,setSelfWords]=useState(''),[tomorrow,setTomorrow]=useState(''),[mapPage,setMapPage]=useState(0);
 useEffect(()=>{if(open){setPage(initialPage);setViewSpecies(state.settings.species);setLetter(null);setRoom(companion.preferences.room);setRoomDirty(false);setSelfWords(companion.daily[day]?.selfWords??'');setTomorrow(companion.daily[day]?.tomorrow??'')}},[open,initialPage,day]);
 const prefs=companion.preferences,pet=companion.pets[viewSpecies],current=companion.pets[state.settings.species],currentView=viewSpecies===state.settings.species;
 const question=dailyQuestion(day),talk=current?.talks[day],episodes=companion.journey.episodes.filter(episode=>episode.species===state.settings.species),episode=companion.journey.episodes.find(item=>item.id===selectedEpisode)??episodes.at(-1),totalWalking=walkingJourney(state.entries),lastMap=Math.floor(totalWalking/180),visibleMap=Math.min(mapPage,lastMap);
 const gifts=companion.gifts.filter(item=>item.species===viewSpecies),wishlist=outfits.find(item=>item.id===prefs.wishlist),letters=pet?lettersFor(pet,day,state.settings.weeklyDays):[];
 const command=(value:CompanionAction)=>onCommand(value);
 async function saveRoom(){const saved=await command({action:'preference',patch:{room}});if(saved)setRoomDirty(false);return saved;}
 function roomChange<K extends keyof RoomDesign>(key:K,value:RoomDesign[K]){setRoom({...room,[key]:value});setRoomDirty(true);}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="app-dialog companion-hub"><DialogTitle>もちと過ごす、やさしい時間</DialogTitle><DialogDescription>好きなところだけ。何もしない日も、いつでも一緒。</DialogDescription><div className="hub-navigation" aria-label="もちとの時間のメニュー">{pages.map(([id,label,Icon])=><Button type="button" key={id} variant={page===id?'secondary':'outline'} aria-pressed={page===id} onClick={()=>{setPage(id);setLetter(null)}}><Icon size={15}/>{label}</Button>)}</div>
  {page==='profile'&&<section className="hub-profile">
   <div className="species-memory-switch" aria-label="3匹の思い出">{pets.map(item=><Button type="button" key={item.id} variant={viewSpecies===item.id?'secondary':'outline'} aria-pressed={viewSpecies===item.id} onClick={()=>{setViewSpecies(item.id);setLetter(null)}}>{item.name}</Button>)}</div>
   {pet?<><div className="profile-card"><Pet species={viewSpecies} outfit={currentView?state.settings.outfit:'none'} pose={1} small/><div><h3>{pet.name}の自己紹介</h3><p>出会った日：{pet.met.replaceAll('-',' / ')}</p><p>{personalities.find(item=>item[0]===pet.personality)?.[1]} · 好きな遊び：{pet.likes.activity??'これから見つけよう'}</p><p>触れ合いのあしあと：{bondCount(pet)}<Heart size={13}/></p></div></div><Button type="button" variant="ghost" onClick={()=>setPage('gifts')}>この子がくれた思い出の品を見る</Button>{!currentView&&<Button type="button" variant="outline" disabled={disabled} onClick={async()=>{if(await onSwitch(viewSpecies))setViewSpecies(viewSpecies)}}>この子に会う</Button>}
   {letter?<article className="mochi-letter"><Cake size={27}/><h3>{letter.title}</h3><p>{letter.text}</p><Button type="button" variant="ghost" onClick={()=>setLetter(null)}>もちのことに戻る</Button></article>:<>
    <section className="comfort-panel"><h3>この子らしさ</h3><label>性格<select aria-label="もちの性格" value={pet.personality} disabled={disabled||!currentView} onChange={event=>void command({action:'personality',value:event.target.value as typeof pet.personality})}>{personalities.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="likes-grid">{memoryQuestions.map(item=><label key={item.key}>{({fruit:'好きな果物',season:'好きな季節',activity:'好きな過ごし方',color:'好きな色',weather:'好きな音',flower:'好きな花'})[item.key]}<select aria-label={({'fruit':'好きな果物','season':'好きな季節','activity':'好きな過ごし方','color':'好きな色','weather':'好きな音','flower':'好きな花'})[item.key]} value={pet.likes[item.key]??''} disabled={disabled||!currentView} onChange={event=>void command({action:'like',key:item.key,value:event.target.value})}><option value="" disabled>これから見つけよう</option>{item.options.map(value=><option key={value}>{value}</option>)}</select></label>)}</div></section>
    <section className="comfort-panel"><h3>きみと、もちのこと</h3><label>呼ばれたい名前<input aria-label="呼ばれたい名前" maxLength={12} defaultValue={prefs.callingName} key={prefs.callingName} disabled={disabled} onBlur={event=>{if(event.target.value.trim()!==prefs.callingName)void command({action:'preference',patch:{callingName:event.target.value.trim()}})}} placeholder="呼び名なしでも大丈夫"/></label><label>言葉の温度<select aria-label="もちの言葉の温度" value={prefs.tone} disabled={disabled} onChange={event=>void command({action:'preference',patch:{tone:event.target.value as typeof prefs.tone}})}>{tones.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p>会わない日があっても、なかよしのあしあとは減らないよ。</p><div className={'bond-cuddle bond-'+bondLevel(pet)}><Heart size={21}/><span>{['ここから、少しずつ','少し近くで、のんびり','そばへ、すりすり','おひざのそばで、ぎゅっ'][bondLevel(pet)]}</span></div></section>
    <section className="comfort-panel"><h3>もちからのお手紙</h3>{letters.length?letters.map(item=><Button type="button" variant="outline" key={item.id} disabled={disabled} onClick={()=>{setLetter(item);if(currentView)void command({action:'readLetter',id:item.id})}}><BookOpen size={16}/>{item.title}{pet.lettersRead.includes(item.id)&&<span className="subtle">読んだお手紙</span>}</Button>):<p>一緒に過ごした日が積もると、7日・30日のお手紙や、出会った日の小さなお祝いが届くよ。</p>}</section>
    <section className="comfort-panel"><h3>この子との、小さな発見</h3>{pet.discoveries.length?<ul className="memory-list">{pet.discoveries.slice().reverse().slice(0,archive?undefined:8).map((item,index)=><li key={item.day+index}><time>{item.day.slice(5).replace('-','/')}</time>{item.text}</li>)}</ul>:<p>なでたり遊んだり、おさんぽしたり。ここに思い出が残っていくよ。</p>}<Button type="button" variant="ghost" onClick={()=>setArchive(!archive)}>{archive?'最近の思い出に戻る':'これまでの思い出を見る'}</Button></section>
   </>}</>:<div className="comfort-panel"><Pet species={viewSpecies} small/><p>この子とのはじめましても、好きなときに。</p><Button type="button" variant="outline" disabled={disabled} onClick={()=>void onSwitch(viewSpecies)}>この子に会う</Button></div>}
  </section>}
  {page==='talk'&&<div className="hub-talk">
   <section className="comfort-panel"><h3>今、ほしい寄り添い方</h3><div className="choice-row">{supports.map(([id,label])=><Button type="button" key={id} disabled={disabled} variant={prefs.support===id?'secondary':'outline'} aria-pressed={prefs.support===id} onClick={()=>void command({action:'preference',patch:{support:id}})}>{label}</Button>)}</div><p>{prefs.support==='rest'?'何もしない時間も、そばにいるよ。':prefs.support==='cheer'?'ひとつだけでも、きみのペースを応援するよ。':'聞かせたいことがあったら、きみの言葉で。'}</p>{prefs.support==='listen'&&<Button type="button" variant="outline" onClick={()=>{onOpenChange(false);onNote()}}>もちにメモを書く</Button>}</section>
   <section className="comfort-panel daily-talk"><h3>今日の、短いお話</h3><div className="talk-pet"><Pet species={state.settings.species} outfit={state.settings.outfit} pose={1} small/></div><p>{question.question}</p><div className="choice-row">{question.options.map((value,index)=><Button type="button" key={value} disabled={disabled} aria-pressed={talk?.value===value} variant={talk?.value===value?'secondary':'outline'} onClick={()=>void command({action:'talk',choice:index})}>{value}</Button>)}</div><p aria-live="polite">{talk?`「${talk.value}」、覚えているよ。次のお話でも一緒に思い出そうね。`:'答えなくても大丈夫。ここで聞くだけでも。'}</p><Button type="button" variant="ghost" onClick={()=>setPage('profile')}>あとで話そう</Button></section>
   <section className="comfort-panel"><h3>今の目標を、小さな一歩に</h3><p>{state.settings.goal||'自分のペースで過ごす'}</p><strong>{goalStep(state.settings.goal)}</strong><p>試すかどうかも、今日は自分で選んでね。</p>{companion.daily[day]?.step?<p className="selected-step" role="status">今日、選んだ一歩：{companion.daily[day].step}</p>:<Button type="button" variant="outline" disabled={disabled} onClick={()=>void command({action:'step'})}>今日の一歩に選ぶ</Button>}<Button type="button" variant="outline" onClick={()=>setPage('rest')}>もちとひと息つく</Button></section>
   {companion.daily[daysAgo(day,1)]?.tomorrow&&<section className="comfort-panel"><h3>昨日、選んだ小さな楽しみ</h3><p>{companion.daily[daysAgo(day,1)].tomorrow}</p><p>気が変わっても大丈夫。今日の自分のペースで。</p></section>}
   <section className="comfort-panel bedtime-panel"><h3><Moon size={17}/>おやすみの、ひとこと</h3><label>今日の自分へ<input aria-label="今日の自分へひとこと" maxLength={160} value={selfWords} onChange={event=>setSelfWords(event.target.value)} placeholder="書かずにおやすみでも大丈夫"/></label><div className="choice-row">{['今日も、おつかれさま','休めた自分にも、ありがとう','少しできた、それで十分'].map(text=><Button type="button" variant="ghost" key={text} onClick={()=>setSelfWords(text)}>{text}</Button>)}</div><label>明日の小さな楽しみ<input aria-label="明日の小さな楽しみ" maxLength={80} value={tomorrow} onChange={event=>setTomorrow(event.target.value)} placeholder="もちとお茶、絵本、窓辺でひと息…"/></label><div className="choice-row">{['明日はもちとお茶','明日は好きな絵本をひらく','明日は窓辺でひと息'].map(text=><Button type="button" variant="ghost" key={text} onClick={()=>setTomorrow(text)}>{text}</Button>)}</div><Button type="button" disabled={disabled} onClick={async()=>{if(await onBedtime(selfWords,tomorrow))onOpenChange(false)}}>もちと、おやすみ</Button></section>
  </div>}
  {page==='journey'&&<div className="hub-journey">
   <section className="comfort-panel"><h3>次に寄り道する場所</h3><div className="choice-row">{routes.map(([id,label])=><Button type="button" key={id} disabled={disabled} variant={companion.journey.route===id?'secondary':'outline'} aria-pressed={companion.journey.route===id} onClick={()=>void command({action:'route',route:id})}>{label}</Button>)}</div><p>好きな場所を、いつでも選び直せるよ。</p></section>
   <section className="comfort-panel walking-map"><h3>歩いた時間の、旅の地図</h3><p>これまでに記録した合計 <strong>{totalWalking}分</strong></p><p>分数で景色が増える、架空の地図。実際の距離とは別の、小さな旅。</p><div className={'journey-map route-'+companion.journey.route}>{Array.from({length:7},(_,i)=>{const threshold=visibleMap*180+i*30;return <div className={totalWalking>=threshold?'map-stop reached':'map-stop'} key={i}><span>{i%3===0?<Leaf size={20}/>:i%3===1?<Flower2 size={20}/>:<Home size={20}/>}</span><small>{threshold}分</small></div>})}</div><div className="map-pagination"><Button type="button" variant="ghost" disabled={visibleMap===0} onClick={()=>setMapPage(Math.max(0,visibleMap-1))}><ChevronLeft size={15}/>前の景色</Button><Button type="button" variant="ghost" disabled={visibleMap>=lastMap} onClick={()=>setMapPage(visibleMap+1)}>次の景色<ChevronRight size={15}/></Button></div></section>
   <section className="comfort-panel episode-card"><h3>もちの、おさんぽ物語</h3>{episode?<><span className="episode-npc">{episode.npc}</span><h4>{episode.title}</h4><Pet species={episode.species} outfit={state.settings.outfit} pose={episode.resting?2:0} small/><p>{episode.text}</p><div className="choice-row">{episode.choices.map((value,index)=><Button type="button" key={value} disabled={disabled} variant={episode.answer===index?'secondary':'outline'} aria-pressed={episode.answer===index} onClick={()=>void command({action:'story',id:episode.id,choice:index})}>{value}</Button>)}</div><p>{episode.answer!==null?'この寄り道を、次のお話でも覚えているよ。':'読んで閉じても大丈夫。返事は好きなときに。'}</p><p className="subtle">見つけたおみやげ：{episode.souvenir}。次に会ったときも、なくならずに待っているよ。</p></>:<p>気分、メモ、おさんぽ、またはおやすみを残した日に、短いお話がひとつ進むよ。</p>}</section>
   <details className="comfort-panel story-archive"><summary>これまでのお話を読み返す</summary>{episodes.length?episodes.slice().reverse().map(item=><Button type="button" variant="ghost" key={item.id} onClick={()=>setSelectedEpisode(item.id)}>{item.day.slice(5).replace('-','/')} · {item.title}</Button>):<p>最初のお話を、のんびり待っているよ。</p>}</details>
   <section className="comfort-panel"><h3>いつでも読める、季節のお話</h3>{seasonStories.map(item=><details key={item[0]}><summary>{item[1]}</summary><p>{item[2]}</p></details>)}</section>
   <ActivityTimer scope={scope} onWalking={minutes=>{onOpenChange(false);onWalking(minutes)}} onStretch={()=>{onOpenChange(false);onStretch()}}/>
  </div>}
  {page==='rest'&&<ComfortActivities species={state.settings.species} outfit={state.settings.outfit} preferences={prefs} onPreference={patch=>command({action:'preference',patch})} onInteract={onInteract}/>}
  {page==='room'&&<div className="hub-room">
   <div className="room-preview-live"><PetPlayground species={state.settings.species} outfit={state.settings.outfit} name={state.settings.name} pose={room.furniture==='bed'?2:0} message={roomAction||'今の自分に心地よい、お部屋にしよう。'} quiet compact design={room} hour={hour} plant={plantStage(current)} bond={bondLevel(current)} onInteract={onInteract}/></div>
   <section className="comfort-panel"><h3>お部屋を、少しだけ整える</h3><div className="room-controls">
    <label>床<select aria-label="お部屋の床" value={room.floor} onChange={event=>roomChange('floor',event.target.value as RoomDesign['floor'])}><option value="wood">やわらかな木</option><option value="rug">あったかラグ</option><option value="meadow">小さな草原</option></select></label>
    <label>家具をひとつ<select aria-label="お部屋の家具" value={room.furniture} onChange={event=>roomChange('furniture',event.target.value as RoomDesign['furniture'])}><option value="cushion">クッション</option><option value="bed">ベッド</option><option value="book">絵本</option><option value="ball">ボール</option></select></label>
    <label>天気<select aria-label="お部屋の天気" value={room.weather} onChange={event=>roomChange('weather',event.target.value as RoomDesign['weather'])}><option value="sun">晴れ</option><option value="rain">小雨</option><option value="snow">雪</option></select></label>
    <label>光<select aria-label="お部屋の光" value={room.light} onChange={event=>roomChange('light',event.target.value as RoomDesign['light'])}><option value="auto">今の時間に合わせる</option><option value="morning">朝のひかり</option><option value="evening">夕方のひかり</option><option value="night">夜のひかり</option></select></label>
    <label>好きな季節<select aria-label="お部屋の季節" value={room.season} onChange={event=>roomChange('season',event.target.value as RoomDesign['season'])}><option value="plain">いつものお部屋</option><option value="spring">春の花</option><option value="summer">夏の青空</option><option value="autumn">秋の葉っぱ</option><option value="winter">冬のぬくもり</option></select></label>
    <label>心地よい色<select aria-label="お部屋の色" value={room.palette} onChange={event=>roomChange('palette',event.target.value as RoomDesign['palette'])}><option value="warm">あたたかな色</option><option value="leaf">落ち着く葉の色</option><option value="sky">やわらかな空の色</option><option value="clear">はっきり、見やすい色</option></select></label>
   </div><p>{roomDirty?'選んだお部屋を、上で眺めてみてね。':'今のお部屋は保存されています。'}</p><Button type="button" disabled={disabled||!roomDirty} onClick={()=>void saveRoom()}>お部屋を保存する</Button></section>
   <section className="comfort-panel"><h3>お気に入りのお部屋</h3><label>このお部屋の名前<input aria-label="お気に入りのお部屋の名前" value={favoriteName} maxLength={20} onChange={event=>setFavoriteName(event.target.value)} placeholder="朝の窓辺、夜のお部屋…"/></label><Button type="button" variant="outline" disabled={disabled||!favoriteName.trim()} onClick={async()=>{if(roomDirty&&!await saveRoom())return;if(await command({action:'roomFavorite',name:favoriteName.trim()}))setFavoriteName('')}}>今のお部屋をお気に入りに</Button>{prefs.favorites.map((item,index)=><div className="favorite-room" key={item.name}><Button type="button" variant="outline" disabled={disabled} onClick={async()=>{setRoom(item.design);setRoomDirty(false);if(await command({action:'preference',patch:{room:item.design}}))setRoomAction(item.name+'のお部屋で、のんびり。')}}>{item.name}にする</Button><Button type="button" variant="ghost" disabled={disabled} aria-label={item.name+'をお気に入りから外す'} onClick={()=>void command({action:'removeFavorite',index})}>外す</Button></div>)}</section>
  </div>}
  {page==='gifts'&&<div className="hub-gifts">
   <div className="species-memory-switch" aria-label="贈りものをくれたもち">{pets.map(item=><Button type="button" key={item.id} variant={viewSpecies===item.id?'secondary':'outline'} aria-pressed={viewSpecies===item.id} onClick={()=>setViewSpecies(item.id)}>{item.name}</Button>)}</div>
   <section className="comfort-panel"><h3>もちから、小さな贈りもの</h3><p>最初の触れ合い、記録した日、おさんぽのおみやげ。ゆっくり受け取れるよ。</p>{gifts.length?<div className="keepsake-grid">{gifts.slice().reverse().map(item=><article key={item.id} className={item.opened?'gift-opened':'gift-wrapped'}><span aria-hidden="true">{item.opened?<Flower2 size={28}/>:<Gift size={29}/>}</span><h4>{item.label}</h4><time>{item.day.replaceAll('-',' / ')}</time><p>{item.note}</p>{item.opened?<span className="subtle">大切な思い出に</span>:<Button type="button" variant="outline" disabled={disabled||!item.available} onClick={async()=>{if(await command({action:'openGift',id:item.id}))setOpenedGift(item.id)}}>{item.available?'もちから受け取る':'次に会ったときに'}</Button>}{openedGift===item.id&&<p aria-live="polite">もちが、そっと手渡してくれたよ。</p>}{item.episodeId&&<Button type="button" variant="ghost" onClick={()=>{setSelectedEpisode(item.episodeId!);setPage('journey')}}>このときのお話</Button>}</article>)}</div>:<p>もちをなでたり、今日のひとことを残したり。小さな贈りものが、ここに届くよ。</p>}</section>
   <section className="comfort-panel"><h3>次に会いたい、おめかし</h3><select aria-label="次にほしい衣装" value={prefs.wishlist??''} disabled={disabled} onChange={event=>void command({action:'preference',patch:{wishlist:event.target.value?event.target.value as typeof prefs.wishlist:null}})}><option value="">決めずに、のんびり</option>{outfits.filter(item=>item.id!=='none').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{wishlist&&<div className="wish-card"><Pet species={state.settings.species} outfit={wishlist.id} small/><p>{wishlist.name}<br/>{state.stars>=wishlist.cost?'この姿に会えるよ。':`あと${wishlist.cost-state.stars}こ。自分のペースで。`}</p><progress aria-label="ほしい衣装までの進み具合" max={wishlist.cost||1} value={Math.min(state.stars,wishlist.cost||1)}/></div>}</section>
   <section className="comfort-panel"><h3>好きな季節の小箱</h3><p>季節を過ぎても大丈夫。いつでも、好きな小箱をひらけるよ。</p>{seasonStories.map(item=>{const received=companion.gifts.some(gift=>gift.id==='season:'+item[0]+':'+state.settings.species);return <div className="season-gift" key={item[0]}><p>{item[1]} · {item[3]}</p><Button type="button" variant="outline" disabled={disabled||received} onClick={()=>void command({action:'seasonGift',season:item[0]})}>{received?'大切にしまったよ':'小箱をひらく'}</Button></div>})}</section>
   {allRewardsUnlocked(state.stars)&&<section className="comfort-panel after-story"><h3><Sparkles size={18}/>特別なもちとの、そのあと</h3><Pet species={state.settings.species} outfit="starlight" pose={3} small/>{afterStories.map(([title,text],index)=><details key={title} onToggle={event=>{if(event.currentTarget.open&&!current?.lettersRead.includes('after-'+index))void command({action:'readLetter',id:'after-'+index})}}><summary>{title}</summary><p>{text}</p></details>)}</section>}
  </div>}
 </DialogContent></Dialog>;
}
