'use client';
import { CalendarDays, ChartNoAxesCombined, ChevronRight, Heart, Plus, Pencil, NotebookPen, Moon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { daysAgo, type Entry } from '@/lib/mochi';
import { recentEntries } from '@/lib/history';
import { previousWeight, weightChange, weightDate } from '@/lib/weight';
import { WalkingChart } from './walking-chart';
import { CareCalendar } from './care-calendar';
import { calendarWeek } from '@/lib/care';

const moodNames=['元気！','ふつう','おつかれ'];
export function HistoryView({entries,day,weeklyDays,onEdit,onWeight,onWalking,onNote}:{entries:Entry[];day:string;weeklyDays?:number|null;onEdit:(entry?:Entry)=>void;onWeight:()=>void;onWalking:()=>void;onNote:(entry:Entry)=>void}){
 const recent=recentEntries(entries,day),week=recentEntries(entries,day,7),notes=recent.filter(entry=>entry.note?.trim());
 const records=recent.filter(entry=>entry.weight!==null).slice().reverse(),values=records.map(entry=>entry.weight!);
 const minimum=values.length?Math.min(...values)-.5:0,maximum=values.length?Math.max(...values)+.5:1;
 const y=(value:number)=>130-(value-minimum)/(maximum-minimum)*100;
 const x=(date:string)=>35+(Date.parse(date)-Date.parse(daysAgo(day,29)))/86400000/29*430;
 const measuredWeek=week.filter(entry=>entry.weight!==null),average=measuredWeek.length?(measuredWeek.reduce((sum,entry)=>sum+entry.weight!,0)/measuredWeek.length).toFixed(1):null;
 const calendarDays=calendarWeek(day),weeklyVisits=entries.filter(entry=>entry.care?.visited&&calendarDays.includes(entry.day)).length;
 return <div className="reflection-history">
  <section className="card reflection"><div className="section-heading"><h2><Heart size={17}/>今週できたこと</h2><span className="subtle">直近7日</span></div><strong>{week.length}<small>日</small></strong><p>記録を残せたね。</p><div className="reflection-stat"><span>習慣に取り組んだ回数</span><b>{week.reduce((sum,entry)=>sum+entry.done.length,0)}回</b></div><div className="care-reflection-stats"><span>会えた日 <b>{entries.filter(entry=>entry.care?.visited&&entry.day>=daysAgo(day,6)&&entry.day<=day).length}</b>日</span><span>おやすみの日 <b>{week.filter(entry=>entry.care?.resting).length}</b>日</span></div><p className="support-copy">今週のあしあと · {weeklyDays?"会えた日 "+weeklyVisits+"日 · 週に"+weeklyDays+"日くらいのペース":"会える日に、ゆっくり。"}</p><CareCalendar entries={entries} days={calendarDays} today={day}/><p className="support-copy">記録のない日も、また始められる。ここまでのあしあとは消えないよ。</p></section>
  <section className="card chart-card"><div className="section-heading"><h2>体重のうつりかわり</h2><span className="subtle">直近30日</span></div><div className="average"><span>直近7日の平均</span><strong>{average??'—'}<small>kg</small></strong></div>{records.length?<><svg className="weight-chart" viewBox="0 0 500 175" role="img" aria-label="直近30日の体重推移。各日の値は下の記録一覧で確認できます。">{[minimum,(minimum+maximum)/2,maximum].map(value=><g key={value}><line x1="35" y1={y(value)} x2="475" y2={y(value)} stroke="#eee7e0" strokeDasharray="4 4"/><text x="0" y={y(value)+4} fill="#82766f" fontSize="12">{value.toFixed(1)}</text></g>)}<polyline points={records.map(entry=>`${x(entry.day)},${y(entry.weight!)}`).join(' ')} fill="none" stroke="#dd795b" strokeWidth="3" strokeLinejoin="round"/>{records.map(entry=><circle key={entry.day} cx={x(entry.day)} cy={y(entry.weight!)} r="4" fill="#dd795b"><title>{entry.day}: {entry.weight}kg</title></circle>)}<text x="35" y="163" fontSize="13" fill="#82766f">{daysAgo(day,29).slice(5).replace('-','/')}</text><text x="443" y="163" fontSize="13" fill="#82766f">今日</text></svg><p className="subtle">記録した日の数値を線でつないでいます。</p></>:<div className="empty-chart"><ChartNoAxesCombined size={34}/><p>はじめの記録を待っています</p><span>体重の入力は、気が向いたときに。</span><Button variant="outline" onClick={onWeight}>記録する</Button></div>}</section>
  <WalkingChart entries={entries} day={day} onRecord={onWalking}/>
  <section className="card recent-notes"><div className="section-heading"><h2><NotebookPen size={17}/>メモの推移</h2><span className="subtle">直近30日</span></div>{notes.length?<div className="note-timeline">{notes.map(entry=><article key={entry.day}><div className="section-heading"><time dateTime={entry.day}>{entry.day.replaceAll('-',' / ')}</time><Button variant="ghost" size="sm" aria-label={`${entry.day}のメモを編集`} onClick={()=>onNote(entry)}><Pencil size={14}/>編集</Button></div><p className="note-text">{entry.note}</p></article>)}</div>:<p className="empty-copy">直近のメモはまだありません。今日のひとことから残してね。</p>}</section>
  <section className="card history-list"><div className="section-heading"><h2>これまでの記録</h2><span className="subtle">直近30日</span><Button variant="outline" onClick={()=>onEdit()}><Plus size={16}/>記録を追加</Button></div>{recent.length?recent.map(entry=>{const previous=previousWeight(entries,entry.day);return <button className="history-row" key={entry.day} onClick={()=>onEdit(entry)}><span><CalendarDays size={17}/>{entry.day.replaceAll('-',' / ')}</span><span>{entry.weight!==null?`${entry.weight.toFixed(1)} kg`:'—'}{entry.weight!==null&&previous&&<small className="weight-difference">{weightChange(entry.weight,previous.weight)} · {weightDate(previous.day)}比</small>}{entry.walkingMinutes!=null&&<small className="history-walking">ウォーキング {entry.walkingMinutes}分</small>}{entry.care?.resting&&<small className="history-rest"><Moon size={12}/>おやすみの記録</small>}<small>{entry.mood!==null?moodNames[entry.mood]:entry.care?.resting?'のんびり過ごした日':'気分は余白'} · 習慣 {entry.done.length}つ</small>{!!entry.partial?.length&&<small className="history-partial">少しできた習慣 {entry.partial.length}つ</small>}{(!!entry.feelings?.length||!!entry.tags?.length)&&<small className="history-tags">{[...entry.feelings??[],...entry.tags??[]].join(' · ')}</small>}{entry.note&&<small className="history-note">{entry.note}</small>}</span><ChevronRight size={17}/></button>}):<p className="empty-copy">直近の記録はまだありません。ひとつだけでも、ここに残せます。</p>}</section>
 </div>;
}
