'use client';
import { useRef, useState } from 'react';
import { CalendarDays, ChartNoAxesCombined, ChevronRight, Heart, Plus, Pencil, NotebookPen, Moon, Scale, Footprints, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { daysAgo, type Entry } from '@/lib/mochi';
import { recentEntries } from '@/lib/history';
import { previousWeight, weightChange } from '@/lib/weight';
import { WalkingChart } from './walking-chart';
import { CareCalendar } from './care-calendar';
import { calendarWeek } from '@/lib/care';
import { CollectionPager, slicePage } from './collection-pager';

const moodNames=['元気！','ふつう','おつかれ'];
const views=[['week','今週',Heart],['weight','体重',Scale],['walking','歩いた分',Footprints],['notes','メモ',NotebookPen],['records','記録',CalendarDays]] as const;
type View=typeof views[number][0];
const shortDate=(day:string)=>day.slice(5).replace('-','/');
const blank=(day:string):Entry=>({day,weight:null,walkingMinutes:null,mood:null,done:[],note:''});
export function HistoryView({entries,day,onEdit,onWeight,onWalking,onNote}:{entries:Entry[];day:string;weeklyDays?:number|null;onEdit:(entry?:Entry)=>void;onWeight:()=>void;onWalking:()=>void;onNote:(entry:Entry)=>void}){
 const [view,setView]=useState<View>('week'),[notePage,setNotePage]=useState(0),[recordPage,setRecordPage]=useState(0),[reading,setReading]=useState<Entry|null>(null);
 const sections=useRef<HTMLDivElement>(null);
 const recent=recentEntries(entries,day),week=recentEntries(entries,day,7),notes=recent.filter(entry=>entry.note?.trim());
 const records=recent.filter(entry=>entry.weight!==null).slice().reverse(),values=records.map(entry=>entry.weight!);
 const minimum=values.length?Math.min(...values)-.5:0,maximum=values.length?Math.max(...values)+.5:1;
 const y=(value:number)=>130-(value-minimum)/(maximum-minimum)*100,x=(date:string)=>35+(Date.parse(date)-Date.parse(daysAgo(day,29)))/86400000/29*430;
 const measuredWeek=week.filter(entry=>entry.weight!==null),average=measuredWeek.length?(measuredWeek.reduce((sum,entry)=>sum+entry.weight!,0)/measuredWeek.length).toFixed(1):null;
 const latest=records.at(-1),previous=latest?previousWeight(entries,latest.day):null;
 const walkingWeek=week.filter(entry=>entry.walkingMinutes!=null),walkingTotal=walkingWeek.reduce((sum,entry)=>sum+entry.walkingMinutes!,0);
 const visibleNotes=slicePage(notes,notePage,3),visibleRecords=slicePage(recent,recordPage,5);
 function choose(next:string){setView(next as View);setNotePage(0);setRecordPage(0);}
 function changePage(next:number,kind:'notes'|'records'){if(kind==='notes')setNotePage(next);else setRecordPage(next);sections.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
 return <Tabs ref={sections} value={view} onValueChange={choose} className="reflection-browser collection-browser">
  <TabsList className="collection-tabs reflection-sections" aria-label="ふりかえりの項目">{views.map(([id,label,Icon])=><TabsTrigger key={id} value={id}><Icon size={19}/><span>{label}</span></TabsTrigger>)}</TabsList>
  <TabsContent value="week"><section className="card reflection-summary"><div className="section-heading"><h2>今週できたこと</h2><span className="subtle">直近7日</span></div><div className="week-totals"><div><CalendarDays size={22}/><strong>{week.length}<small>日</small></strong><span>記録を残した日</span></div><div><Check size={22}/><strong>{week.reduce((sum,entry)=>sum+entry.done.length,0)}<small>回</small></strong><span>できた小さな習慣</span></div></div><CareCalendar entries={entries} days={calendarWeek(day)} today={day}/><div className="week-footnotes"><span>会えた日 <b>{entries.filter(entry=>entry.care?.visited&&entry.day>=daysAgo(day,6)&&entry.day<=day).length}</b>日</span><span><Moon size={13}/>おやすみ <b>{week.filter(entry=>entry.care?.resting).length}</b>日</span></div></section><div className="reflection-quick-links"><button type="button" onClick={()=>choose('weight')}><Scale size={21}/><span>最近の体重</span><strong>{latest?.weight?.toFixed(1)??'—'}<small>kg</small></strong><small>{latest&&previous?weightChange(latest.weight!,previous.weight):'体重のグラフを見る'}</small><ChevronRight className="quick-link-arrow" size={16}/></button><button type="button" onClick={()=>choose('walking')}><Footprints size={21}/><span>7日間のウォーキング</span><strong>{walkingWeek.length?walkingTotal:'—'}<small>分</small></strong><small>歩いた時間のグラフを見る</small><ChevronRight className="quick-link-arrow" size={16}/></button></div></TabsContent>
  <TabsContent value="weight"><section className="card chart-card"><div className="section-heading"><h2>体重のうつりかわり</h2><span className="subtle">直近30日</span></div><div className="average"><span>直近7日の平均</span><strong>{average??'—'}<small>kg</small></strong></div>{records.length?<><svg className="weight-chart" viewBox="0 0 500 175" role="img" aria-label="直近30日の体重推移。日付ごとの値は記録の項目から確認できます。">{[minimum,(minimum+maximum)/2,maximum].map(value=><g key={value}><line x1="35" y1={y(value)} x2="475" y2={y(value)} stroke="#eee7e0" strokeDasharray="4 4"/><text x="0" y={y(value)+4} fill="#82766f" fontSize="12">{value.toFixed(1)}</text></g>)}<polyline points={records.map(entry=>`${x(entry.day)},${y(entry.weight!)}`).join(' ')} fill="none" stroke="#dd795b" strokeWidth="3" strokeLinejoin="round"/>{records.map(entry=><circle key={entry.day} cx={x(entry.day)} cy={y(entry.weight!)} r="4" fill="#dd795b"><title>{entry.day}: {entry.weight}kg</title></circle>)}<text x="35" y="163" fontSize="13" fill="#82766f">{shortDate(daysAgo(day,29))}</text><text x="443" y="163" fontSize="13" fill="#82766f">今日</text></svg><div className="metric-recent-values">{records.slice(-3).reverse().map(entry=><span key={entry.day}><time>{shortDate(entry.day)}</time><strong>{entry.weight!.toFixed(1)} kg</strong></span>)}</div><Button type="button" variant="ghost" className="all-records-link" onClick={()=>choose('records')}>日付ごとの記録を見る<ChevronRight size={16}/></Button></>:<div className="empty-chart"><ChartNoAxesCombined size={34}/><p>はじめの記録を待っています</p><Button type="button" variant="outline" onClick={onWeight}>体重を記録する</Button></div>}</section></TabsContent>
  <TabsContent value="walking"><WalkingChart entries={entries} day={day} onRecord={onWalking}/>{recent.some(entry=>entry.walkingMinutes!=null)&&<div className="walking-recent card"><div className="metric-recent-values">{recent.filter(entry=>entry.walkingMinutes!=null).slice(0,3).map(entry=><span key={entry.day}><time>{shortDate(entry.day)}</time><strong>{entry.walkingMinutes}分</strong></span>)}</div><Button type="button" variant="ghost" className="all-records-link" onClick={()=>choose('records')}>日付ごとの記録を見る<ChevronRight size={16}/></Button></div>}</TabsContent>
  <TabsContent value="notes"><section className="card compact-notes"><div className="section-heading"><h2>メモの推移</h2><span className="subtle">直近30日 · {notes.length}件</span></div>{notes.length?<><div className="compact-note-list">{visibleNotes.items.map(entry=><article key={entry.day}><div><time dateTime={entry.day}>{shortDate(entry.day)}</time><Button type="button" variant="ghost" size="sm" aria-label={`${entry.day}のメモを編集`} onClick={()=>onNote(entry)}><Pencil size={15}/></Button></div><button type="button" aria-label={`${entry.day}のメモを読む`} onClick={()=>setReading(entry)}><p>{entry.note}</p><span>全文を読む<ChevronRight size={14}/></span></button></article>)}</div><CollectionPager {...visibleNotes} onChange={page=>changePage(page,'notes')} label="メモ"/></>:<div className="collection-empty"><NotebookPen size={33}/><p>直近のメモはまだありません</p><Button type="button" variant="outline" onClick={()=>onNote(entries.find(entry=>entry.day===day)??blank(day))}>今日のメモを書く</Button></div>}</section></TabsContent>
  <TabsContent value="records"><section className="card compact-records"><div className="section-heading"><h2>これまでの記録</h2><Button type="button" variant="outline" size="sm" onClick={()=>onEdit()}><Plus size={15}/>追加</Button></div><p className="subtle records-period">直近30日 · {recent.length}日</p>{recent.length?<><div className="compact-record-list">{visibleRecords.items.map(entry=><button type="button" key={entry.day} className="compact-record-row" onClick={()=>onEdit(entry)}><span><time dateTime={entry.day}>{shortDate(entry.day)}</time><small>{entry.mood!==null?moodNames[entry.mood]:entry.care?.resting?'おやすみ':'気分は余白'} · 習慣{entry.done.length}つ{entry.partial?.length?` · 途中${entry.partial.length}つ`:''}</small></span><span className="compact-record-metrics"><strong>{entry.weight!==null?`${entry.weight.toFixed(1)} kg`:'— kg'}</strong><small>{entry.walkingMinutes!=null?`${entry.walkingMinutes}分`:''}{entry.note?.trim()&&<NotebookPen size={13} aria-label="メモあり"/>}</small></span><ChevronRight size={17}/></button>)}</div><CollectionPager {...visibleRecords} onChange={page=>changePage(page,'records')} label="記録"/></>:<div className="collection-empty"><CalendarDays size={33}/><p>直近の記録はまだありません</p><Button type="button" variant="outline" onClick={()=>onEdit()}>記録を追加する</Button></div>}</section></TabsContent>
  <Dialog open={reading!==null} onOpenChange={open=>{if(!open)setReading(null)}}><DialogContent className="app-dialog collection-detail memo-reader"><DialogTitle><NotebookPen size={20}/>{reading?reading.day.replaceAll('-',' / '):''}のメモ</DialogTitle><DialogDescription className="sr-only">メモの全文</DialogDescription><div className="collection-detail-body"><p>{reading?.note}</p></div><div className="collection-detail-footer"><Button type="button" variant="outline" onClick={()=>{if(reading){const entry=reading;setReading(null);onNote(entry)}}}><Pencil size={16}/>このメモを編集する</Button></div></DialogContent></Dialog>
 </Tabs>;
}
