'use client';
import { useState, useEffect, useCallback, useRef } from 'react';
import { PawPrint, House, ChartNoAxesCombined, Gift, Settings as SettingsIcon, Star, Heart, Smile, Meh, Moon, Footprints, StretchHorizontal, Utensils, Check, Plus, LockKeyhole, ChevronRight, Scale, CalendarDays, Pencil, LogOut, LoaderCircle, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { defaults, rooms, today, daysAgo, type Entry, type Settings, type State } from '@/lib/mochi';
const moodNames=['元気！','ふつう','おつかれ'];
const MoodIcons=[Smile,Meh,Moon];
function Puppy({pose=0,small=false}:{pose?:number;small?:boolean}){return <div className={'puppy '+(small?'small':'')+' pose-'+pose} role="img" aria-label={['にっこりおすわりする白い子犬','うれしそうに拍手する白い子犬','すやすや眠る白い子犬','目を輝かせてジャンプする白い子犬'][pose]} style={{backgroundPosition:[ '0% 0%','100% 0%','0% 100%','100% 100%'][pose]}}/>}
const blank=(day:string):Entry=>({day,weight:null,mood:null,done:[]});
function hasRecord(e:Entry){return e.weight!==null||e.mood!==null||e.done.length>0;}
export default function MochiApp({signedIn,signInPath}:{signedIn:boolean;signInPath:string}){
 const [state,setState]=useState<State>({entries:[],settings:defaults,stars:0});
 const [loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState('today'),[celebrate,setCelebrate]=useState(false),[petTouch,setPetTouch]=useState(false);
 const [settingsOpen,setSettingsOpen]=useState(false),[editSettings,setEditSettings]=useState<Settings>(defaults),[entryOpen,setEntryOpen]=useState(false),[draft,setDraft]=useState<Entry>(blank(today())),[weight,setWeight]=useState('');
 const [currentDay,setCurrentDay]=useState(today()),[hour,setHour]=useState(12);
 const pending=useRef(false),stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{const tick=()=>{setCurrentDay(today());setHour(Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',hourCycle:'h23'}).format(new Date())))};tick();const timer=setInterval(tick,60000);return()=>clearInterval(timer)},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json() as State & {error?:string};if(!r.ok)throw new Error(d.error);setState(d)}catch(e){setError(e instanceof Error?e.message:'読み込みに失敗しました。')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(signedIn)void load()},[signedIn,load]);
 useEffect(()=>{if(!celebrate&&!petTouch)return;const timer=setTimeout(()=>{setCelebrate(false);setPetTouch(false)},3000);return()=>clearTimeout(timer)},[celebrate,petTouch]);
 const save=useCallback(async(body:unknown,quiet=false)=>{if(pending.current)return false;pending.current=true;setSaving(true);setError('');try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as State & {error?:string};if(!r.ok)throw new Error(d.error);const gained=d.stars-stateRef.current.stars;setState(d);if(gained>0){setCelebrate(true);toast.success(`できたね！ おほしさま ＋${gained}`)}else if(!quiet)toast.success('保存しました');return true}catch(e){const message=e instanceof Error?e.message:'保存できませんでした。';setError(message);toast.error(message);return false}finally{pending.current=false;setSaving(false)}},[]);
 useEffect(()=>{
 const context=(document as any).modelContext;if(!context?.registerTool||!signedIn)return;
 const life=new AbortController();try{Promise.resolve(context.registerTool({name:'open_daily_record',title:'記録画面を開く',description:'指定日の記録フォームを開きます。保存はしません。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=(input as any)?.date;if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d||d>today()||d<'2000-01-01')throw new Error('有効な日付を指定してください');const entry=stateRef.current.entries.find(e=>e.day===d)??blank(d);setDraft({...entry,done:[...entry.done]});setWeight(entry.weight?.toString()??'');setEntryOpen(true);return {opened:true,date:d,saved:false}}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[signedIn]);
 const entry=state.entries.find(e=>e.day===currentDay)??blank(currentDay),settings=state.settings;
 const week=Array.from({length:7},(_,i)=>daysAgo(currentDay,6-i));
 const weekEntries=state.entries.filter(e=>week.includes(e.day)&&hasRecord(e));
 const allDays=state.entries.filter(hasRecord).length;
 const night=hour>=21||hour<6;
 const pose=celebrate?3:petTouch?1:(entry.mood===2||night)?2:entry.done.length===settings.habits.length?1:0;
 const message=celebrate?'できたね！ いっしょに、ばんざい。':petTouch?'なでてくれて、うれしいな。':entry.mood===2?'今日はゆっくり。そばにいるよ。':night?'今日もおつかれさま。ゆっくり休もう。':allDays===0?'はじめまして。きみのペースでいこうね。':'おかえり！ 今日も会えてうれしいな。';
 const room=rooms.find(r=>r.id===settings.room)??rooms[0],nextRoom=rooms.find(r=>r.cost>state.stars);
 function openEntry(e:Entry=entry){setDraft({...e,done:[...e.done]});setWeight(e.weight?.toString()??'');setEntryOpen(true)}
 async function submitEntry(ev:React.FormEvent){ev.preventDefault();const num=weight.trim()===''?null:Number(weight);if(num!==null&&(!Number.isFinite(num)||num<1||num>500)){toast.error('体重は1〜500kgの範囲で入力してください。');return}if(await save({kind:'entry',...draft,weight:num}))setEntryOpen(false)}
 function changeDate(day:string){const e=state.entries.find(e=>e.day===day)??blank(day);setDraft({...e,done:[...e.done]});setWeight(e.weight?.toString()??'')}
 function openSettings(){setEditSettings({...settings,habits:[...settings.habits]});setSettingsOpen(true)}
 const records=state.entries.filter(e=>e.weight!==null&&e.day>=daysAgo(currentDay,29)).slice().reverse();
 const values=records.map(e=>e.weight!);const min=values.length?Math.min(...values)-.5:0,max=values.length?Math.max(...values)+.5:1;
 const y=(v:number)=>130-(v-min)/(max-min)*100;
 const x=(day:string)=>35+(Date.parse(day)-Date.parse(daysAgo(currentDay,29)))/86400000/29*430;
 const avg=weekEntries.filter(e=>e.weight!==null);const average=avg.length?(avg.reduce((s,e)=>s+e.weight!,0)/avg.length).toFixed(1):null;
 if(!signedIn)return <div className="login-wrap"><header className="brand"><span className="brand-mark"><PawPrint/></span>もちと、まいにち</header><main className="login-card"><div className="eyebrow">MY LITTLE COMPANION</div><Puppy/><h1>きょうの小さな「できた」を、<br/>いっしょに。</h1><p>体重も、気分も、毎日の習慣も。<br/>あなたのペースを、もちが応援します。</p><Button className="login-button" asChild><a href={signInPath} target="_top"><LockKeyhole size={18}/>ChatGPTでログイン</a></Button><p className="privacy"><LockKeyhole size={14}/>招待された方だけの、プライベートな記録</p></main><footer className="login-footer">おやすみの日があっても、いつでもおかえり。</footer></div>;
 return <div className="app-shell"><Toaster position="top-center" theme="light"/><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><PawPrint/></span><span>もちと、まいにち<small>MY LITTLE COMPANION</small></span></a><div className="header-right"><span className="private-tag"><LockKeyhole size={13}/>あなただけの記録</span><Button variant="ghost" size="icon" className="settings-button" aria-label="設定を開く" onClick={openSettings} disabled={loading||!!error}><SettingsIcon size={20}/></Button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="main-nav" aria-label="メインメニュー"><TabsTrigger value="today"><House/>きょう</TabsTrigger><TabsTrigger value="history"><ChartNoAxesCombined/>ふりかえり</TabsTrigger><TabsTrigger value="rewards"><Gift/>ごほうび</TabsTrigger></TabsList>
 <main className="main-content"><div className="page-heading"><div><p className="date-line">{new Date(currentDay+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Tokyo'})}</p><h1>{tab==='today'?'きょうも、自分のペースで。':tab==='history'?'少しずつ、つづいてる。':'小さなできたが、たからもの。'}</h1></div><div className="star-total"><Star size={19} fill="currentColor"/><strong>{state.stars}</strong><span>おほしさま</span></div></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span>{!loading&&<Button variant="outline" onClick={load}>再読み込み</Button>}</div>}
 {loading?<div className="loading-grid" aria-label="記録を読み込み中"><Skeleton className="h-96 rounded-3xl"/><Skeleton className="h-96 rounded-3xl"/></div>:<>
 <TabsContent value="today"><div className="today-grid"><section className="companion-card" style={{backgroundColor:room.color}}><div className="companion-top"><span className="small-label"><Heart size={15}/>{settings.name}のお部屋</span><span className="room-label">{room.name}</span></div><div className="speech" aria-live="polite">{message}</div><button className={'pet-button '+(celebrate?'celebrating':'')} onClick={()=>setPetTouch(true)} aria-label={`${settings.name}をなでる`}><Puppy pose={pose}/></button><p className="pet-name">{settings.name}<Heart size={14}/></p><p className="pet-caption">タップして、なでてみてね</p><div className="together"><PawPrint size={20}/><span>いっしょに記録した日</span><strong>{allDays}<small>日</small></strong></div></section>
 <div className="daily-panels"><section className="card mood-card"><div className="section-heading"><h2>いま、どんな気分？</h2><span className="subtle">ひとつ選んでね</span></div><RadioGroup className="mood-options" value={entry.mood===null?'':String(entry.mood)} onValueChange={v=>void save({kind:'entry',...entry,mood:Number(v)},true)} disabled={saving||!!error}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(entry.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={31}/><span>{moodNames[i]}</span>{entry.mood===i&&<Check size={13} className="mood-check"/>}</label>)}</RadioGroup></section>
 <section className="card habits-card"><div className="section-heading"><h2>きょうの小さな習慣</h2><Button variant="ghost" size="sm" onClick={openSettings} aria-label="習慣を編集"><Pencil size={14}/>編集</Button></div><p className="support-copy">ひとつできたら、それだけで花まる。</p><div className="habit-list">{settings.habits.map((habit,i)=>{const Icon=[Footprints,StretchHorizontal,Utensils][i],checked=entry.done.includes('h'+i);return <label className={'habit '+(checked?'completed':'')} key={i}><span className={'habit-icon habit-'+i}><Icon size={21}/></span><span>{habit}</span><Checkbox aria-label={habit} checked={checked} disabled={saving||!!error} onCheckedChange={v=>void save({kind:'entry',...entry,done:v?[...entry.done,'h'+i]:entry.done.filter(h=>h!=='h'+i)},true)} className="habit-check"/></label>})}</div><div className="habit-summary"><Progress value={entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length/settings.habits.length*100} aria-label="今日の習慣の達成度"/><span>{entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length} / {settings.habits.length}</span></div></section>
 {settings.showWeight&&<section className="card weight-card"><div className="weight-icon"><Scale size={22}/></div><div><h2>きょうの体重 <span className="optional">任意</span></h2><p className="weight-value">{entry.weight===null?'—':entry.weight.toFixed(1)}<span>kg</span></p></div><Button variant="outline" onClick={()=>openEntry()} disabled={saving||!!error}>{entry.weight===null?<Plus size={16}/>:<Pencil size={16}/>}記録する</Button></section>}
 </div></div><section className="week-strip"><div><h2>今週のあしあと</h2><p>{weekEntries.length?`${weekEntries.length}日、じぶんに目を向けられたね。`:'今日から、ひとつずつ。'}</p></div><div className="week-days">{week.map(day=>{const yes=state.entries.some(e=>e.day===day&&hasRecord(e));return <div className={'week-day '+(day===currentDay?'current':'')} key={day}><span>{new Date(day+'T12:00:00Z').toLocaleDateString('ja-JP',{weekday:'short'})}</span><span className={'stamp '+(yes?'filled':'')}>{yes?<PawPrint size={18}/>:<span>·</span>}</span></div>})}</div></section><p className="kind-note"><Heart size={14}/>がんばる日も、おやすみの日も。もちと一緒に。</p></TabsContent>
 <TabsContent value="history"><div className="history-grid"><section className="card chart-card"><div className="section-heading"><h2>体重のうつりかわり</h2><span className="subtle">直近30日</span></div><div className="average"><span>直近7日の平均</span><strong>{average??'—'}<small>kg</small></strong></div>{records.length?<><svg className="weight-chart" viewBox="0 0 500 175" role="img" aria-label="直近30日の体重推移。各日の値は下の記録一覧で確認できます。">{[min,(min+max)/2,max].map(v=><g key={v}><line x1="35" y1={y(v)} x2="475" y2={y(v)} stroke="#eee7e0" strokeDasharray="4 4"/><text x="0" y={y(v)+4} fill="#82766f" fontSize="12">{v.toFixed(1)}</text></g>)}<polyline points={records.map(e=>`${x(e.day)},${y(e.weight!)}`).join(' ')} fill="none" stroke="#dd795b" strokeWidth="3" strokeLinejoin="round"/>{records.map(e=><circle key={e.day} cx={x(e.day)} cy={y(e.weight!)} r="4" fill="#dd795b"><title>{e.day}: {e.weight}kg</title></circle>)}<text x="35" y="163" fontSize="13" fill="#82766f">{daysAgo(currentDay,29).slice(5).replace('-','/')}</text><text x="443" y="163" fontSize="13" fill="#82766f">今日</text></svg><p className="subtle">記録した日の数値を線でつないでいます。</p></>:<div className="empty-chart"><ChartNoAxesCombined size={34}/><p>はじめの記録を待っています</p><span>体重の入力は、気が向いたときに。</span><Button variant="outline" onClick={()=>openEntry()}>記録する</Button></div>}</section><section className="card reflection"><div className="small-label"><Heart size={16}/>今週できたこと</div><strong>{weekEntries.length}<small>日</small></strong><p>記録を残せたね。</p><div className="reflection-stat"><span>習慣に取り組んだ回数</span><b>{weekEntries.reduce((s,e)=>s+e.done.length,0)}回</b></div><p className="support-copy">記録のない日も、また始められる。<br/>ここまでのあしあとは消えないよ。</p></section></div><section className="card history-list"><div className="section-heading"><h2>これまでの記録</h2><Button variant="outline" onClick={()=>openEntry()}><Plus size={16}/>記録を追加</Button></div>{state.entries.filter(hasRecord).length?state.entries.filter(hasRecord).map(e=><button className="history-row" key={e.day} onClick={()=>openEntry(e)}><span><CalendarDays size={17}/>{e.day.replaceAll('-',' / ')}</span><span>{e.weight!==null?`${e.weight.toFixed(1)} kg`:'—'}<small>{e.mood!==null?moodNames[e.mood]:'気分未記録'} · 習慣 {e.done.length}つ</small></span><ChevronRight size={17}/></button>):<p className="empty-copy">まだ記録はありません。ひとつだけでも、ここに残せます。</p>}</section></TabsContent>
 <TabsContent value="rewards"><section className="reward-intro"><div className="reward-star"><Star fill="currentColor" size={32}/></div><div><h2>集めたおほしさま <strong>{state.stars}<small>こ</small></strong></h2><p>気分・体重・習慣の記録で、それぞれ1日1こ。<br/>一度集めたおほしさまは、減りません。</p></div></section>{nextRoom&&<div className="next-reward"><span>次のお部屋まで、あと <b>{nextRoom.cost-state.stars}こ</b></span><Progress value={state.stars/nextRoom.cost*100}/></div>}<div className="rooms-grid">{rooms.map((r,i)=>{const unlocked=state.stars>=r.cost,selected=settings.room===r.id;return <section className={'room-card '+(selected?'chosen':'')} key={r.id}><div className="room-preview" style={{backgroundColor:r.color}}><Puppy small pose={i}/>{!unlocked&&<span className="room-lock"><LockKeyhole size={18}/>{r.cost}こでひらく</span>}</div><div className="room-details"><h3>{r.name}</h3><Button variant={selected?'secondary':'outline'} disabled={!unlocked||selected||saving||!!error} onClick={()=>void save({kind:'settings',...settings,room:r.id})}>{selected?<><Check size={15}/>使用中</>:unlocked?'このお部屋にする':<><Star size={15}/>{r.cost}こ</>}</Button></div></section>})}</div><p className="kind-note"><Heart size={14}/>おほしさまは、体重の増減ではなく「できた」のしるし。</p></TabsContent>
 </>}
 </main></Tabs>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="app-dialog"><DialogTitle>あなたと、相棒のこと</DialogTitle><DialogDescription>心地よく続けられる形にしよう。</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await save({kind:'settings',...editSettings}))setSettingsOpen(false)}}><label className="field-label" htmlFor="pet-name">相棒の名前</label><Input id="pet-name" value={editSettings.name} maxLength={12} required onChange={e=>setEditSettings({...editSettings,name:e.target.value})}/><div className="field-label">毎日の習慣 <span className="subtle">最大3つ</span></div><p className="subtle">無理なくできそうなことを選んでね。</p><div className="habit-edit">{editSettings.habits.map((h,i)=><Input key={i} aria-label={`習慣${i+1}`} value={h} maxLength={30} required onChange={e=>setEditSettings({...editSettings,habits:editSettings.habits.map((v,j)=>i===j?e.target.value:v)})}/>)}</div><div className="habit-edit-actions">{editSettings.habits.length<3&&<Button type="button" variant="outline" onClick={()=>setEditSettings({...editSettings,habits:[...editSettings.habits,'']})}><Plus size={15}/>習慣を追加</Button>}{editSettings.habits.length>1&&<Button type="button" variant="ghost" onClick={()=>setEditSettings({...editSettings,habits:editSettings.habits.slice(0,-1)})}>最後の習慣を外す</Button>}</div><label className="switch-label" htmlFor="show-weight"><span>ホームに体重を表示</span><Switch id="show-weight" checked={editSettings.showWeight} onCheckedChange={v=>setEditSettings({...editSettings,showWeight:v})}/></label><p className="subtle">日本時間で日付が切り替わります。</p><Button className="save-button" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>}保存する</Button></form><div className="account-footer"><LockKeyhole size={14}/><span>記録はログインした本人だけが見られます。</span></div><a className="logout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/>ログアウト</a></DialogContent></Dialog>
 <Dialog open={entryOpen} onOpenChange={setEntryOpen}><DialogContent className="app-dialog"><DialogTitle>きょうの記録</DialogTitle><DialogDescription>どれかひとつだけでも、大丈夫。</DialogDescription><form onSubmit={submitEntry}><label className="field-label" htmlFor="entry-day">日付</label><Input type="date" id="entry-day" required value={draft.day} min="2000-01-01" max={currentDay} onChange={e=>changeDate(e.target.value)}/><label className="field-label" htmlFor="weight">体重 <span className="subtle">任意・kg</span></label><Input id="weight" type="number" inputMode="decimal" step="0.1" min="1" max="500" placeholder="例：60.0" value={weight} onChange={e=>setWeight(e.target.value)}/><div className="field-label">気分</div><RadioGroup className="mood-options" value={draft.mood===null?'':String(draft.mood)} onValueChange={v=>setDraft({...draft,mood:Number(v)})}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(draft.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={26}/><span>{moodNames[i]}</span></label>)}</RadioGroup><div className="field-label">できた習慣</div>{settings.habits.map((h,i)=><label className="draft-habit" key={i}><Checkbox checked={draft.done.includes('h'+i)} onCheckedChange={v=>setDraft({...draft,done:v?[...draft.done,'h'+i]:draft.done.filter(x=>x!=='h'+i)})}/>{h}</label>)}<Button className="save-button" disabled={saving||!draft.day}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>}記録を保存する</Button></form></DialogContent></Dialog>
 </div>
}
