'use client';
import { useState, useEffect, useCallback, useRef } from 'react';
import { PawPrint, House, ChartNoAxesCombined, Gift, Settings as SettingsIcon, Star, Heart, Smile, Meh, Moon, Footprints, StretchHorizontal, Utensils, Check, Plus, LockKeyhole, ChevronRight, Scale, CalendarDays, Pencil, LogOut, LoaderCircle, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PilotTools } from './pilot-tools';
import { WeightPicker } from './weight-picker';
import { latestWeight, previousWeight, weightDraft, weightChange, weightDate } from '@/lib/weight';
import { requestState } from '@/lib/api-client';
import { requestDeviceState } from '@/lib/device-store';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { defaults, rooms, today, daysAgo, type Entry, type Settings, type State, pets, outfits, expressionNames, petSprite, type Species, type Outfit } from '@/lib/mochi';
const moodNames=['元気！','ふつう','おつかれ'];
const MoodIcons=[Smile,Meh,Moon];
const habitSuggestions=['1分ストレッチ','深呼吸5回','コップ1杯の水を飲む','窓を開けて換気する','ベッドを整える','野菜を1品食べる','机の上を片付ける','好きな曲を1曲聴く','今日良かったことを1つ書く'];
// "/" on Sites, "/mochi-days/" on GitHub Pages.
const base=import.meta.env.BASE_URL;
function Pet({species='dog',pose=0,outfit='none',small=false}:{species?:Species;pose?:number;outfit?:Outfit;small?:boolean}){
 const sprite=petSprite(species,pose,outfit,base+'pets'),column=sprite.cell%sprite.columns,row=Math.floor(sprite.cell/sprite.columns);
 // The original puppy sheet has more padding; zoom each cell around its center.
 const scale=sprite.columns===2?1.1:1,width=sprite.columns*scale,height=sprite.rows*scale;
 // The jumping puppy sits high in its cell; leave room above its tuft.
 const offsetY=scale>1&&sprite.cell===3?0.07:0;
 return <div className={'puppy pet-art '+(small?'small':'')} role="img" aria-label={`${pets.find(p=>p.id===species)?.name}・${outfit==='none'?expressionNames[pose]:(sprite.cell%2?'ごきげん':'にっこり')}・${outfits.find(o=>o.id===outfit)?.name}`} style={{backgroundImage:`url('${sprite.src}')`,backgroundSize:`${width*100}% ${height*100}%`,backgroundPosition:`${((column+.5)*scale-.5)/(width-1)*100}% ${((row+.5)*scale-.5-offsetY)/(height-1)*100}%`}}/>;
}
function PetPicker({value,onChange,disabled=false}:{value:Species;onChange:(value:Species)=>void;disabled?:boolean}){
 return <RadioGroup className="pet-picker" value={value} onValueChange={v=>onChange(v as Species)} disabled={disabled} aria-label="相棒を選ぶ">{pets.map(p=><label key={p.id} className={'pet-choice '+(value===p.id?'selected':'')}><RadioGroupItem value={p.id} className="sr-only"/><Pet species={p.id}/><strong>{p.name}</strong><span>{p.description}</span>{value===p.id&&<Check className="choice-check" size={18}/>}</label>)}</RadioGroup>;
}
const blank=(day:string):Entry=>({day,weight:null,mood:null,done:[],note:''});
function hasRecord(e:Entry){return e.weight!==null||e.mood!==null||e.done.length>0||!!e.note?.trim();}
function WeightDifference({record,entries}:{record:Entry;entries:Entry[]}){
 const previous=previousWeight(entries,record.day);
 return record.weight!==null&&previous?<small className="weight-difference">{weightChange(record.weight,previous.weight)} · {weightDate(previous.day)}比</small>:null;
}
export default function MochiApp({signedIn,signInPath='',storage='server'}:{signedIn:boolean;signInPath?:string;storage?:'server'|'device'}){
 const onDevice=storage==='device',request=onDevice?requestDeviceState:requestState;
 // iPhone Safari keeps a separate storage for the Home Screen app, so choose where to start before recording.
 const safariTab=onDevice&&(navigator as Navigator&{standalone?:boolean}).standalone===false;
 const [state,setState]=useState<State>({entries:[],settings:defaults,stars:0});
 const [loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState('today'),[celebrate,setCelebrate]=useState(false),[petTouch,setPetTouch]=useState(false);
 const [settingsOpen,setSettingsOpen]=useState(false),[editSettings,setEditSettings]=useState<Settings>(defaults),[entryOpen,setEntryOpen]=useState(false),[draft,setDraft]=useState<Entry>(blank(today())),[weight,setWeight]=useState('');
 const [weightIncluded,setWeightIncluded]=useState(false),[weightOnly,setWeightOnly]=useState(false),[petTap,setPetTap]=useState(0);
 const [failedBody,setFailedBody]=useState<unknown>(null),[offline,setOffline]=useState(false),[unlockReaction,setUnlockReaction]=useState(false);
 const [loaded,setLoaded]=useState(false);
 const [chosenSpecies,setChosenSpecies]=useState<Species>('dog'),[chosenName,setChosenName]=useState('もち'),[demoPose,setDemoPose]=useState<number|null>(null);
 const [currentDay,setCurrentDay]=useState(today()),[hour,setHour]=useState(12);
 const pending=useRef(false),stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{const tick=()=>{setCurrentDay(today());setHour(Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',hourCycle:'h23'}).format(new Date())))};tick();const timer=setInterval(tick,60000);return()=>clearInterval(timer)},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await request();setState(d);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'読み込みに失敗しました。')}finally{setLoading(false)}},[request]);
 useEffect(()=>{if(signedIn)void load()},[signedIn,load]);
 useEffect(()=>{if(!celebrate&&!petTouch)return;const timer=setTimeout(()=>{setCelebrate(false);setPetTouch(false)},3000);return()=>clearTimeout(timer)},[celebrate,petTouch,petTap]);
 const save=useCallback(async(body:unknown,quiet=false)=>{if(pending.current)return false;pending.current=true;setSaving(true);setError('');try{const d=await request(body);setFailedBody(null);const gained=d.stars-stateRef.current.stars;
 const newlyOpened=outfits.filter(o=>o.cost>stateRef.current.stars&&o.cost<=d.stars);
 const openedRoom=rooms.some(r=>r.cost>stateRef.current.stars&&r.cost<=d.stars);
 setState(d);setDemoPose(null);setPetTouch(false);if(openedRoom||newlyOpened.length)setUnlockReaction(true);if(newlyOpened.length)toast.success(`新しい衣装がひらいたよ：${newlyOpened.map(o=>o.name).join('・')}`);if(gained>0){setCelebrate(true);toast.success(`できたね！ おほしさま ＋${gained}`)}else if(!quiet)toast.success('保存しました');return true}catch(e){setFailedBody(body);const message=e instanceof Error?e.message:'保存できませんでした。';setError(message);toast.error(message);return false}finally{pending.current=false;setSaving(false)}},[request]);
 useEffect(()=>{
 const context=(document as any).modelContext;if(!context?.registerTool||!signedIn)return;
 const life=new AbortController();try{Promise.resolve(context.registerTool({name:'open_daily_record',title:'記録画面を開く',description:'指定日の記録フォームを開きます。保存はしません。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=(input as any)?.date;if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d||d>today()||d<'2000-01-01')throw new Error('有効な日付を指定してください');const entry=stateRef.current.entries.find(e=>e.day===d)??blank(d);prepareEntry(entry);setWeightOnly(false);setEntryOpen(true);return {opened:true,date:d,saved:false}}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[signedIn]);
 useEffect(()=>{if(demoPose===null)return;const timer=setTimeout(()=>setDemoPose(null),5000);return()=>clearTimeout(timer)},[demoPose]);
 useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[]);
 useEffect(()=>{if(!unlockReaction)return;const timer=setTimeout(()=>setUnlockReaction(false),1200);return()=>clearTimeout(timer)},[unlockReaction]);
 useEffect(()=>{if(!saving&&failedBody===null)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[saving,failedBody]);
 const entry=state.entries.find(e=>e.day===currentDay)??blank(currentDay),settings=state.settings;
 const weightRecord=entry.weight!==null?entry:latestWeight(state.entries,currentDay),draftPreviousWeight=previousWeight(state.entries,draft.day);
 const week=Array.from({length:7},(_,i)=>daysAgo(currentDay,6-i));
 const weekEntries=state.entries.filter(e=>week.includes(e.day)&&hasRecord(e));
 const allDays=state.entries.filter(hasRecord).length;
 const night=hour>=21||hour<6;
 const pose=demoPose??(petTouch?1:unlockReaction?6:celebrate?3:entry.mood===2?7:night?2:settings.habits.every((_,i)=>entry.done.includes('h'+i))?5:entry.mood===0?4:0);
 const message=demoPose!==null?`${expressionNames[demoPose]}。いろんな顔で、そばにいるよ。`:petTouch?'なでてくれて、うれしいな。':unlockReaction?'わあ、新しいごほうびがひらいたよ！':celebrate?'できたね！ いっしょに、ばんざい。':entry.mood===2?'今日はゆっくり。そばにいるよ。':night?'今日もおつかれさま。ゆっくり休もう。':allDays===0?'はじめまして。きみのペースでいこうね。':'おかえり！ 今日も会えてうれしいな。';
 const room=rooms.find(r=>r.id===settings.room)??rooms[0],nextRoom=rooms.find(r=>r.cost>state.stars);
 function prepareEntry(e:Entry,recordWeight=false){const candidate=weightDraft(stateRef.current.entries,e,recordWeight);setDraft({...e,done:[...e.done]});setWeight(candidate.value);setWeightIncluded(candidate.included)}
 function openEntry(e:Entry=entry,recordWeight=false){prepareEntry(e,recordWeight);setWeightOnly(recordWeight);setEntryOpen(true)}
 async function submitEntry(ev:React.FormEvent){ev.preventDefault();const num=weightIncluded?(weight.trim()===''?NaN:Number(weight)):null;if(num!==null&&(!Number.isFinite(num)||num<1||num>500)){toast.error('体重は1〜500kgの範囲で入力してください。');return}const savedEntry=weightOnly?(stateRef.current.entries.find(e=>e.day===draft.day)??blank(draft.day)):draft;if(await save({kind:'entry',...savedEntry,weight:num}))setEntryOpen(false)}
 function changeDate(day:string){const e=state.entries.find(e=>e.day===day)??blank(day);prepareEntry(e,weightIncluded)}
 function openSettings(){setEditSettings({...settings,habits:[...settings.habits]});setSettingsOpen(true)}
 const records=state.entries.filter(e=>e.weight!==null&&e.day>=daysAgo(currentDay,29)).slice().reverse();
 const values=records.map(e=>e.weight!);const min=values.length?Math.min(...values)-.5:0,max=values.length?Math.max(...values)+.5:1;
 const y=(v:number)=>130-(v-min)/(max-min)*100;
 const x=(day:string)=>35+(Date.parse(day)-Date.parse(daysAgo(currentDay,29)))/86400000/29*430;
 const avg=weekEntries.filter(e=>e.weight!==null);const average=avg.length?(avg.reduce((s,e)=>s+e.weight!,0)/avg.length).toFixed(1):null;
 if(!signedIn)return <div className="login-wrap"><header className="brand"><span className="brand-mark"><PawPrint/></span>もちと、まいにち</header><main className="login-card"><div className="eyebrow">MY LITTLE COMPANION</div><Pet/><h1>きょうの小さな「できた」を、<br/>いっしょに。</h1><p>体重も、気分も、毎日の習慣も。<br/>あなたのペースを、もちが応援します。</p><Button className="login-button" asChild><a href={signInPath} target="_top"><LockKeyhole size={18}/>ChatGPTでログイン</a></Button><p className="privacy"><LockKeyhole size={14}/>招待された方だけの、プライベートな記録</p></main><a className="install-link" href={base+'install'}>ホーム画面への追加・使い方</a><footer className="login-footer">おやすみの日があっても、いつでもおかえり。</footer></div>;
 if(signedIn&&!loading&&loaded&&!settings.onboardingComplete)return <div className="onboarding"><Toaster position="top-center" theme="light"/><header className="brand"><span className="brand-mark"><PawPrint/></span>もちと、まいにち</header><main><p className="eyebrow">はじめまして、これからよろしくね</p><h1>まいにちを、一緒に過ごす相棒。</h1><p className="onboarding-copy">気になる子を選んで、名前をつけてね。<br/>あとから設定で変えることもできます。</p>{safariTab&&<p className="device-hint">ホーム画面から使うなら、先にホーム画面に追加してから始めてね。Safariとホーム画面のもちでは、記録が別々に保存されます。<a href={base+'install'}>追加のしかた</a></p>}{error&&<p className="error-banner" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();await save({kind:'settings',...settings,species:chosenSpecies,name:chosenName.trim(),onboardingComplete:true},true)}}><PetPicker value={chosenSpecies} onChange={setChosenSpecies} disabled={saving}/><div className="onboarding-name"><label className="field-label" htmlFor="first-pet-name">相棒の名前</label><Input id="first-pet-name" value={chosenName} required maxLength={12} onChange={e=>setChosenName(e.target.value)} disabled={saving}/><Button className="save-button" disabled={saving||!chosenName.trim()}>{saving?<LoaderCircle className="spin"/>:<PawPrint size={19}/>}この子とはじめる</Button></div></form><p className="kind-note">がんばる日も、おやすみの日も。いつも味方だよ。</p></main></div>;
 return <div className="app-shell"><Toaster position="top-center" theme="light"/><header className="topbar"><a href={base} className="brand"><span className="brand-mark"><PawPrint/></span><span>もちと、まいにち<small>MY LITTLE COMPANION</small></span></a><div className="header-right"><span className="private-tag"><LockKeyhole size={13}/>あなただけの記録</span><Button variant="ghost" size="icon" className="settings-button" aria-label="設定を開く" onClick={openSettings} disabled={loading||!loaded||saving||failedBody!==null}><SettingsIcon size={20}/></Button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="main-nav" aria-label="メインメニュー"><TabsTrigger value="today"><House/>きょう</TabsTrigger><TabsTrigger value="history"><ChartNoAxesCombined/>ふりかえり</TabsTrigger><TabsTrigger value="rewards"><Gift/>ごほうび</TabsTrigger></TabsList>
 <main className="main-content"><div className="page-heading"><div><p className="date-line">{new Date(currentDay+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Tokyo'})}</p><h1>{tab==='today'?'きょうも、自分のペースで。':tab==='history'?'少しずつ、つづいてる。':'小さなできたが、たからもの。'}</h1></div><div className="star-total"><Star size={19} fill="currentColor"/><strong>{state.stars}</strong><span>おほしさま</span></div></div>
 {offline&&!onDevice&&<p className="connection-banner" role="status">いまはオフラインです。記録の保存には接続が必要です。</p>}{saving&&<p className="save-status" role="status"><LoaderCircle className="spin" size={16}/>保存を確認しています…</p>}{error&&<div className="error-banner" role="alert"><span>{error}</span>{!loading&&(failedBody!==null?<div className="retry-actions"><Button variant="outline" disabled={saving} onClick={()=>void save(failedBody)}>前の操作をもう一度保存</Button><small>未送信の入力はこの画面に残っています。閉じる前に保存してください。</small></div>:<Button variant="outline" onClick={load}>再読み込み</Button>)}</div>}
 {loading?<div className="loading-grid" aria-label="記録を読み込み中"><Skeleton className="h-96 rounded-3xl"/><Skeleton className="h-96 rounded-3xl"/></div>:<>
 <TabsContent value="today"><div className="today-grid"><section className="companion-card" style={{backgroundColor:room.color}}><div className="companion-top"><span className="small-label"><Heart size={15}/>{settings.name}のお部屋</span><span className="room-label">{room.name}</span></div><div className="speech" aria-live="polite">{message}</div><button className={'pet-button '+(celebrate?'celebrating':'')} onClick={()=>{setDemoPose(null);setPetTouch(true);setPetTap(n=>n+1)}} aria-label={`${settings.name}をなでる`}><Pet species={settings.species} pose={pose} outfit={settings.outfit}/>{petTouch&&<span className="pet-hearts" key={petTap} aria-hidden="true">{[0,1,2].map(n=><Heart key={n} className={'pet-heart pet-heart-'+n} fill="currentColor" size={22}/>)}</span>}</button><p className="pet-name">{settings.name}<Heart size={14}/></p><p className="pet-caption">タップして、なでてみてね</p><div className="expression-buttons" aria-label="相棒の表情を見てみる">{(settings.outfit==='none'?[4,5,6,2]:[0,1]).map(n=><button key={n} type="button" aria-pressed={demoPose===n} onClick={()=>setDemoPose(n)}>{expressionNames[n]}</button>)}</div><div className="together"><PawPrint size={20}/><span>いっしょに記録した日</span><strong>{allDays}<small>日</small></strong></div></section>
 <div className="daily-panels"><section className="card mood-card"><div className="section-heading"><h2>いま、どんな気分？</h2><span className="subtle">ひとつ選んでね</span></div><RadioGroup className="mood-options" value={entry.mood===null?'':String(entry.mood)} onValueChange={v=>void save({kind:'entry',...entry,mood:Number(v)},true)} disabled={saving||!!error||!loaded}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(entry.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={31}/><span>{moodNames[i]}</span>{entry.mood===i&&<Check size={13} className="mood-check"/>}</label>)}</RadioGroup></section>
 <section className="card habits-card"><div className="section-heading"><h2>きょうの小さな習慣</h2><Button variant="ghost" size="sm" onClick={openSettings} aria-label="習慣を編集"><Pencil size={14}/>編集</Button></div><p className="support-copy">ひとつできたら、それだけで花まる。</p><div className="habit-list">{settings.habits.map((habit,i)=>{const Icon=[Footprints,StretchHorizontal,Utensils][i],checked=entry.done.includes('h'+i);return <label className={'habit '+(checked?'completed':'')} key={i}><span className={'habit-icon habit-'+i}><Icon size={21}/></span><span>{habit}</span><Checkbox aria-label={habit} checked={checked} disabled={saving||!!error||!loaded} onCheckedChange={v=>void save({kind:'entry',...entry,done:v?[...entry.done,'h'+i]:entry.done.filter(h=>h!=='h'+i)},true)} className="habit-check"/></label>})}</div><div className="habit-summary"><Progress value={entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length/settings.habits.length*100} aria-label="今日の習慣の達成度"/><span>{entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length} / {settings.habits.length}</span></div></section>
 {settings.showWeight&&<section className="card weight-card"><div className="weight-icon"><Scale size={22}/></div><div className="weight-card-copy"><h2>{entry.weight!==null||!weightRecord?'きょうの体重':'前回の体重'} <span className="optional">任意</span></h2><p className="weight-value">{weightRecord?.weight?.toFixed(1)??'—'}<span>kg</span></p>{weightRecord&&<><WeightDifference record={weightRecord} entries={state.entries}/>{entry.weight===null&&<small className="weight-carried">{weightDate(weightRecord.day)}の記録 · 今日はまだ未記録</small>}</>}</div><Button variant="outline" onClick={()=>openEntry(entry,true)} disabled={saving||!!error||!loaded}>{entry.weight===null?<Plus size={16}/>:<Pencil size={16}/>} {entry.weight===null?'記録する':'編集する'}</Button></section>}
 </div></div><section className="card daily-note"><div className="section-heading"><h2>きょうのひとこと</h2><Button variant="outline" disabled={saving||!!error||!loaded} onClick={()=>openEntry()}>メモを書く</Button></div><p className={entry.note?'note-text':'support-copy'}>{entry.note||'食べたもの、今日よかったこと。なんでも残してね。'}</p></section><section className="week-strip"><div><h2>今週のあしあと</h2><p>{weekEntries.length?`${weekEntries.length}日、じぶんに目を向けられたね。`:'今日から、ひとつずつ。'}</p></div><div className="week-days">{week.map(day=>{const yes=state.entries.some(e=>e.day===day&&hasRecord(e));return <div className={'week-day '+(day===currentDay?'current':'')} key={day}><span>{new Date(day+'T12:00:00Z').toLocaleDateString('ja-JP',{weekday:'short'})}</span><span className={'stamp '+(yes?'filled':'')}>{yes?<PawPrint size={18}/>:<span>·</span>}</span></div>})}</div></section><p className="kind-note"><Heart size={14}/>がんばる日も、おやすみの日も。{settings.name}と一緒に。</p></TabsContent>
 <TabsContent value="history"><div className="history-grid"><section className="card chart-card"><div className="section-heading"><h2>体重のうつりかわり</h2><span className="subtle">直近30日</span></div><div className="average"><span>直近7日の平均</span><strong>{average??'—'}<small>kg</small></strong></div>{records.length?<><svg className="weight-chart" viewBox="0 0 500 175" role="img" aria-label="直近30日の体重推移。各日の値は下の記録一覧で確認できます。">{[min,(min+max)/2,max].map(v=><g key={v}><line x1="35" y1={y(v)} x2="475" y2={y(v)} stroke="#eee7e0" strokeDasharray="4 4"/><text x="0" y={y(v)+4} fill="#82766f" fontSize="12">{v.toFixed(1)}</text></g>)}<polyline points={records.map(e=>`${x(e.day)},${y(e.weight!)}`).join(' ')} fill="none" stroke="#dd795b" strokeWidth="3" strokeLinejoin="round"/>{records.map(e=><circle key={e.day} cx={x(e.day)} cy={y(e.weight!)} r="4" fill="#dd795b"><title>{e.day}: {e.weight}kg</title></circle>)}<text x="35" y="163" fontSize="13" fill="#82766f">{daysAgo(currentDay,29).slice(5).replace('-','/')}</text><text x="443" y="163" fontSize="13" fill="#82766f">今日</text></svg><p className="subtle">記録した日の数値を線でつないでいます。</p></>:<div className="empty-chart"><ChartNoAxesCombined size={34}/><p>はじめの記録を待っています</p><span>体重の入力は、気が向いたときに。</span><Button variant="outline" onClick={()=>openEntry(entry,true)}>記録する</Button></div>}</section><section className="card reflection"><div className="small-label"><Heart size={16}/>今週できたこと</div><strong>{weekEntries.length}<small>日</small></strong><p>記録を残せたね。</p><div className="reflection-stat"><span>習慣に取り組んだ回数</span><b>{weekEntries.reduce((s,e)=>s+e.done.length,0)}回</b></div><p className="support-copy">記録のない日も、また始められる。<br/>ここまでのあしあとは消えないよ。</p></section></div><section className="card history-list"><div className="section-heading"><h2>これまでの記録</h2><Button variant="outline" onClick={()=>openEntry()}><Plus size={16}/>記録を追加</Button></div>{state.entries.filter(hasRecord).length?state.entries.filter(hasRecord).map(e=><button className="history-row" key={e.day} onClick={()=>openEntry(e)}><span><CalendarDays size={17}/>{e.day.replaceAll('-',' / ')}</span><span>{e.weight!==null?`${e.weight.toFixed(1)} kg`:'—'}<WeightDifference record={e} entries={state.entries}/><small>{e.mood!==null?moodNames[e.mood]:'気分未記録'} · 習慣 {e.done.length}つ</small>{e.note&&<small className="history-note">{e.note}</small>}</span><ChevronRight size={17}/></button>):<p className="empty-copy">まだ記録はありません。ひとつだけでも、ここに残せます。</p>}</section></TabsContent>
 <TabsContent value="rewards"><section className="reward-intro"><div className="reward-star"><Star fill="currentColor" size={32}/></div><div><h2>集めたおほしさま <strong>{state.stars}<small>こ</small></strong></h2><p>気分・体重・習慣の記録で、それぞれ1日1こ。<br/>一度集めたおほしさまは、減りません。</p></div></section>{nextRoom&&<div className="next-reward"><span>次のお部屋まで、あと <b>{nextRoom.cost-state.stars}こ</b></span><Progress value={state.stars/nextRoom.cost*100}/></div>}<h2 className="reward-section-title">お部屋</h2><div className="rooms-grid">{rooms.map((r,i)=>{const unlocked=state.stars>=r.cost,selected=settings.room===r.id;return <section className={'room-card '+(selected?'chosen':'')} key={r.id}><div className="room-preview" style={{backgroundColor:r.color}}><Pet species={settings.species} small pose={i} outfit={settings.outfit}/>{!unlocked&&<span className="room-lock"><LockKeyhole size={18}/>{r.cost}こでひらく</span>}</div><div className="room-details"><h3>{r.name}</h3><Button variant={selected?'secondary':'outline'} disabled={!unlocked||selected||saving||!!error} onClick={()=>void save({kind:'settings',...settings,room:r.id})}>{selected?<><Check size={15}/>使用中</>:unlocked?'このお部屋にする':<><Star size={15}/>{r.cost}こ</>}</Button></div></section>})}</div><section className="wardrobe"><div className="section-heading"><div><h2>相棒のクローゼット</h2><p className="support-copy">ひらいた衣装は、何度でも着替えられるよ。</p></div><span className="subtle">{outfits.filter(o=>o.cost<=state.stars).length-1} / 8 解放</span></div><div className="rooms-grid outfit-grid">{outfits.map(o=>{const unlocked=state.stars>=o.cost,selected=settings.outfit===o.id;return <section className={'room-card '+(selected?'chosen':'')} key={o.id}><div className="room-preview outfit-preview"><Pet species={settings.species} outfit={o.id} small pose={selected?1:0}/>{!unlocked&&<span className="room-lock"><LockKeyhole size={16}/>あと {o.cost-state.stars}こ</span>}</div><div className="room-details"><h3>{o.name}</h3><p className="outfit-note">{o.note}</p><Button variant={selected?'secondary':'outline'} disabled={!unlocked||selected||saving||!!error} onClick={async()=>{if(await save({kind:'settings',...settings,outfit:o.id},true)){setPetTouch(true);toast.success(`${o.name}に着替えたよ`)}}}>{selected?<><Check size={15}/>着ているよ</>:unlocked?'これを着る':<><Star size={15}/>{o.cost}こでひらく</>}</Button></div></section>})}</div><p className="support-copy wardrobe-note">衣装を着ていても、なでたり記録したりするとにっこり。おほしさまは使っても減りません。</p></section><section className="expression-album card"><h2>{settings.name}の、いろんな顔</h2><p className="support-copy">いつものすがたで8つの表情。衣装にはそれぞれ2つの表情があります。</p><div className="expression-grid">{expressionNames.map((name,i)=><figure key={name}><Pet species={settings.species} pose={i} small/><figcaption>{name}</figcaption></figure>)}</div></section><p className="kind-note"><Heart size={14}/>おほしさまは、体重の増減ではなく「できた」のしるし。</p></TabsContent>
 </>}
 </main></Tabs>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="app-dialog"><DialogTitle>あなたと、相棒のこと</DialogTitle><DialogDescription>心地よく続けられる形にしよう。</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await save({kind:'settings',...editSettings}))setSettingsOpen(false)}}><div className="field-label">相棒の種類</div><PetPicker value={editSettings.species} onChange={species=>setEditSettings({...editSettings,species})} disabled={saving}/><p className="support-copy">相棒を変えても、記録・おほしさま・衣装はそのまま。</p><label className="field-label" htmlFor="pet-name">相棒の名前</label><Input id="pet-name" value={editSettings.name} maxLength={12} required onChange={e=>setEditSettings({...editSettings,name:e.target.value})}/><div className="field-label">毎日の習慣 <span className="subtle">最大3つ</span></div><p className="subtle">無理なくできそうなことを選んでね。</p><div className="habit-edit">{editSettings.habits.map((h,i)=><div className="habit-edit-row" key={i}><Input aria-label={`習慣${i+1}`} value={h} maxLength={30} required onChange={e=>setEditSettings({...editSettings,habits:editSettings.habits.map((v,j)=>i===j?e.target.value:v)})}/><select aria-label={`習慣${i+1}の候補`} value="" onChange={e=>{const choice=e.target.value;if(choice)setEditSettings({...editSettings,habits:editSettings.habits.map((v,j)=>i===j?choice:v)})}}><option value="">候補から選ぶ</option>{habitSuggestions.map(s=><option key={s} value={s}>{s}</option>)}</select></div>)}</div><div className="habit-edit-actions">{editSettings.habits.length<3&&<Button type="button" variant="outline" onClick={()=>setEditSettings({...editSettings,habits:[...editSettings.habits,'']})}><Plus size={15}/>習慣を追加</Button>}{editSettings.habits.length>1&&<Button type="button" variant="ghost" onClick={()=>setEditSettings({...editSettings,habits:editSettings.habits.slice(0,-1)})}>最後の習慣を外す</Button>}</div><label className="switch-label" htmlFor="show-weight"><span>ホームに体重を表示</span><Switch id="show-weight" checked={editSettings.showWeight} onCheckedChange={v=>setEditSettings({...editSettings,showWeight:v})}/></label><p className="subtle">日本時間で日付が切り替わります。</p><Button className="save-button" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>}保存する</Button></form><PilotTools screen={{today:'きょう',history:'ふりかえり',rewards:'ごほうび'}[tab]??tab} storage={storage}/><a className="install-link" href={base+'install'}>ホーム画面への追加・使い方</a><div className="account-footer"><LockKeyhole size={14}/><span>{onDevice?'記録はこの端末のブラウザの中にだけ保存されます。':'記録はログインした本人だけが見られます。'}</span></div>{!onDevice&&<a className="logout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/>ログアウト</a>}</DialogContent></Dialog>
 <Dialog open={entryOpen} onOpenChange={setEntryOpen}>
 <DialogContent className={'app-dialog '+(weightOnly?'weight-only-dialog':'')}>
 <DialogTitle>{weightOnly?(draft.weight!==null?'体重を編集':'体重を記録'):draft.day===currentDay?'きょうの記録':draft.day.replaceAll('-',' / ')+'の記録'}</DialogTitle>
 <DialogDescription>{weightOnly?'上下にスクロールして、今日の体重に合わせてね。':'どれかひとつだけでも、大丈夫。'}</DialogDescription>
 <form onSubmit={submitEntry}>
 {weightOnly?<p className="weight-record-day">{new Date(draft.day+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',timeZone:'Asia/Tokyo'})}の体重</p>:<><label className="field-label" htmlFor="entry-day">日付</label><Input type="date" id="entry-day" required value={draft.day} min="2000-01-01" max={currentDay} onChange={e=>changeDate(e.target.value)}/></>}
 <WeightPicker value={weight} included={weightIncluded} previous={draftPreviousWeight} disabled={saving} optional={!weightOnly} onChange={setWeight} onIncludedChange={setWeightIncluded}/>
 {!weightOnly&&<>
 <div className="field-label">気分</div><RadioGroup className="mood-options" value={draft.mood===null?'':String(draft.mood)} onValueChange={v=>setDraft({...draft,mood:Number(v)})}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(draft.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={26}/><span>{moodNames[i]}</span></label>)}</RadioGroup>
 <div className="field-label">できた習慣</div>{settings.habits.map((h,i)=><label className="draft-habit" key={i}><Checkbox checked={draft.done.includes('h'+i)} onCheckedChange={v=>setDraft({...draft,done:v?[...draft.done,'h'+i]:draft.done.filter(x=>x!=='h'+i)})}/>{h}</label>)}
 <label className="field-label" htmlFor="daily-note">自由メモ <span className="subtle">任意・2000文字まで</span></label><Textarea id="daily-note" value={draft.note??''} maxLength={2000} rows={4} placeholder="今日よかったこと、食べたもの、明日の自分へ。" onChange={e=>setDraft({...draft,note:e.target.value})}/><p className="subtle note-count">{(draft.note??'').length} / 2000</p>
 </>}
 {error&&<p role="alert" className="form-error">{error}<br/>入力は残っています。下のボタンから再保存できます。</p>}
 <Button className="save-button" disabled={saving||!draft.day}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>} {weightOnly?'体重を保存する':'記録を保存する'}</Button>
 </form>
 </DialogContent></Dialog>
 </div>
}
