'use client';
import { useState, useEffect, useCallback, useRef } from 'react';
import { PawPrint, House, ChartNoAxesCombined, Gift, Flower2, Settings as SettingsIcon, Star, Heart, Smile, Meh, Moon, Footprints, StretchHorizontal, Utensils, Check, Plus, LockKeyhole, Scale, Pencil, LogOut, LoaderCircle, Sparkles, Target } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PilotTools } from './pilot-tools';
import { WeightPicker } from './weight-picker';
import { WalkingPicker } from './walking-picker';
import { HistoryView } from './history-view';
import { RewardGallery } from './reward-gallery';
import { Pet } from './pet';
import { PetPlayground, WaitingPet } from './pet-playground';
import { CareCalendar } from './care-calendar';
import { calendarWeek, careFor, visitDays, welcomeKind, welcomeText, smallerGoals, type WelcomeKind } from '@/lib/care';
import { hasRecord } from '@/lib/history';
import { GoalPicker } from './goal-picker';
import { goalOptions } from '@/lib/goals';
import { previousWalking } from '@/lib/walking';
import { latestWeight, previousWeight, weightDraft, weightChange, weightDate } from '@/lib/weight';
import { requestState } from '@/lib/api-client';
import { requestDeviceState } from '@/lib/device-store';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { defaults, rooms, today, type Entry, type Settings, type State, type CareDay, pets, outfits, expressionNames, type Species } from '@/lib/mochi';
const moodNames=['元気！','ふつう','おつかれ'];
const MoodIcons=[Smile,Meh,Moon];
const habitSuggestions=['1分ストレッチ','深呼吸5回','コップ1杯の水を飲む','窓を開けて換気する','ベッドを整える','野菜を1品食べる','机の上を片付ける','好きな曲を1曲聴く','今日良かったことを1つ書く'];
// "/" on Sites, "/mochi-days/" on GitHub Pages.
const base=import.meta.env.BASE_URL;
function PetPicker({value,onChange,disabled=false}:{value:Species;onChange:(value:Species)=>void;disabled?:boolean}){
 return <RadioGroup className="pet-picker" value={value} onValueChange={v=>onChange(v as Species)} disabled={disabled} aria-label="相棒を選ぶ">{pets.map(p=><label key={p.id} className={'pet-choice '+(value===p.id?'selected':'')}><RadioGroupItem value={p.id} className="sr-only"/><Pet species={p.id}/><strong>{p.name}</strong><span>{p.description}</span>{value===p.id&&<Check className="choice-check" size={18}/>}</label>)}</RadioGroup>;
}
const blank=(day:string):Entry=>({day,weight:null,walkingMinutes:null,mood:null,done:[],note:''});
function WeeklyPace({value,onChange,disabled=false}:{value:number|null;onChange:(value:number|null)=>void;disabled?:boolean}){
 return <label className="weekly-pace">もちと過ごすペース<select aria-label="もちと過ごすペース" value={value??''} disabled={disabled} onChange={event=>onChange(event.target.value?Number(event.target.value):null)}><option value="">会える日に、ゆっくり</option>{Array.from({length:7},(_,i)=><option value={i+1} key={i}>週に{i+1}日くらい</option>)}</select><small>曜日は自由。おやすみの日があっても大丈夫。</small></label>;
}
function WeightDifference({record,entries}:{record:Entry;entries:Entry[]}){
 const previous=previousWeight(entries,record.day);
 return record.weight!==null&&previous?<small className="weight-difference">{weightChange(record.weight,previous.weight)} · {weightDate(previous.day)}比</small>:null;
}
export default function MochiApp({signedIn,signInPath='',storage='server'}:{signedIn:boolean;signInPath?:string;storage?:'server'|'device'}){
 const onDevice=storage==='device',request=onDevice?requestDeviceState:requestState;
 // iPhone Safari keeps a separate storage for the Home Screen app, so choose where to start before recording.
 const safariTab=onDevice&&(navigator as Navigator&{standalone?:boolean}).standalone===false;
 const [state,setState]=useState<State>({entries:[],settings:defaults,stars:0});
 const [loading,setLoading]=useState(signedIn),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState('today'),[celebrate,setCelebrate]=useState(false);
 const [settingsOpen,setSettingsOpen]=useState(false),[editSettings,setEditSettings]=useState<Settings>(defaults),[entryOpen,setEntryOpen]=useState(false),[draft,setDraft]=useState<Entry>(blank(today())),[weight,setWeight]=useState('');
 const [weightIncluded,setWeightIncluded]=useState(false),[recordMode,setRecordMode]=useState<'daily'|'weight'|'walking'|'note'>('daily');
 const [walkingMinutes,setWalkingMinutes]=useState('0'),[walkingIncluded,setWalkingIncluded]=useState(false);
 const [goalOpen,setGoalOpen]=useState(false),[goalDraft,setGoalDraft]=useState(''),[chosenGoal,setChosenGoal]=useState<string>(goalOptions[0].text);
 const [loungeOpen,setLoungeOpen]=useState(false),[moreHabits,setMoreHabits]=useState(false),[showRestRecords,setShowRestRecords]=useState(false),[smallGoalOpen,setSmallGoalOpen]=useState(false),[welcome,setWelcome]=useState<WelcomeKind>('first'),[weeklyDraft,setWeeklyDraft]=useState<number|null>(null);
 const weightOnly=recordMode==='weight',walkingOnly=recordMode==='walking',noteOnly=recordMode==='note',singleFieldOnly=recordMode!=='daily';
 const [failedBody,setFailedBody]=useState<unknown>(null),[offline,setOffline]=useState(false),[unlockReaction,setUnlockReaction]=useState(false);
 const [loaded,setLoaded]=useState(false);
 const [chosenSpecies,setChosenSpecies]=useState<Species>('dog'),[chosenName,setChosenName]=useState('もち'),[demoPose,setDemoPose]=useState<number|null>(null);
 const [currentDay,setCurrentDay]=useState(today()),[hour,setHour]=useState(12);
 const pending=useRef(false),stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{const tick=()=>{setCurrentDay(today());setHour(Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',hourCycle:'h23'}).format(new Date())))};tick();const timer=setInterval(tick,60000);return()=>clearInterval(timer)},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await request();setState(d);setWelcome(welcomeKind(d.entries,today()));setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'読み込みに失敗しました。')}finally{setLoading(false)}},[request]);
 useEffect(()=>{if(signedIn)void load()},[signedIn,load]);
 useEffect(()=>{if(!celebrate)return;const timer=setTimeout(()=>setCelebrate(false),3000);return()=>clearTimeout(timer)},[celebrate]);
 const save=useCallback(async(body:unknown,quiet=false)=>{if(pending.current)return false;pending.current=true;setSaving(true);setError('');try{const d=await request(body);setFailedBody(null);const gained=d.stars-stateRef.current.stars;
 const newlyOpened=outfits.filter(o=>o.cost>stateRef.current.stars&&o.cost<=d.stars);
 const openedRoom=rooms.some(r=>r.cost>stateRef.current.stars&&r.cost<=d.stars);
 setState(d);setDemoPose(null);if(openedRoom||newlyOpened.length)setUnlockReaction(true);if(newlyOpened.length)toast.success(`新しい衣装がひらいたよ：${newlyOpened.map(o=>o.name).join('・')}`);if(gained>0){setCelebrate(true);toast.success(`できたね！ おほしさま ＋${gained}`)}else if(!quiet)toast.success('保存しました');if((body as {kind?:string})?.kind==='entry')setCelebrate(true);return true}catch(e){setFailedBody(body);const message=e instanceof Error?e.message:'保存できませんでした。';setError(message);toast.error(message);return false}finally{pending.current=false;setSaving(false)}},[request]);
 useEffect(()=>{
 const context=(document as any).modelContext;if(!context?.registerTool||!signedIn)return;
 const life=new AbortController();try{Promise.resolve(context.registerTool({name:'open_daily_record',title:'記録画面を開く',description:'指定日の記録フォームを開きます。保存はしません。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=(input as any)?.date;if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d||d>today()||d<'2000-01-01')throw new Error('有効な日付を指定してください');const entry=stateRef.current.entries.find(e=>e.day===d)??blank(d);prepareEntry(entry);setRecordMode('daily');setEntryOpen(true);return {opened:true,date:d,saved:false}}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[signedIn]);
 useEffect(()=>{if(demoPose===null)return;const timer=setTimeout(()=>setDemoPose(null),5000);return()=>clearTimeout(timer)},[demoPose]);
 useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[]);
 useEffect(()=>{if(!unlockReaction)return;const timer=setTimeout(()=>setUnlockReaction(false),1200);return()=>clearTimeout(timer)},[unlockReaction]);
 useEffect(()=>{if(!saving&&failedBody===null)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[saving,failedBody]);
 const entry=state.entries.find(e=>e.day===currentDay)??blank(currentDay),settings=state.settings;
 const weightRecord=entry.weight!==null?entry:latestWeight(state.entries,currentDay),draftPreviousWeight=previousWeight(state.entries,draft.day),draftPreviousWalking=previousWalking(state.entries,draft.day);
 const week=calendarWeek(currentDay);
 const weekEntries=state.entries.filter(e=>week.includes(e.day)&&hasRecord(e));
 const allDays=state.entries.filter(hasRecord).length;
 const care=careFor(entry),visits=visitDays(state.entries),weeklyVisits=visits.filter(day=>week.includes(day)).length;
 const panelsOpen=!care.finished&&(!care.resting||showRestRecords);
 useEffect(()=>{setMoreHabits(false);setShowRestRecords(false);setWelcome(welcomeKind(stateRef.current.entries,currentDay))},[currentDay]);
 useEffect(()=>{if(loaded&&signedIn&&settings.onboardingComplete&&!entry.care?.visited&&!saving&&!error&&!pending.current)void save({kind:'care',day:currentDay,visited:true},true)},[loaded,signedIn,settings.onboardingComplete,entry.care?.visited,saving,error,currentDay,save]);
 const night=hour>=21||hour<6;
 const pose=demoPose??(unlockReaction?6:celebrate?3:entry.mood===2?7:night?2:settings.habits.every((_,i)=>entry.done.includes('h'+i))?5:entry.mood===0?4:0);
 const expressionLabel=(n:number)=>settings.outfit==='none'?expressionNames[n]:settings.outfit==='starlight'?({0:'にっこり',3:'ばんざい',2:'すやすや',6:'きらめき'} as Record<number,string>)[n]??'ばんざい':n===0?'にっこり':'よろこび';
 const message=care.finished?'今日はここまでで、花まる。会いに来てくれて、ありがとう。':demoPose!==null?`${expressionLabel(demoPose)}。いろんな顔で、そばにいるよ。`:unlockReaction?'わあ、新しいごほうびがひらいたよ！':celebrate?'できたね！ いっしょに、ばんざい。':entry.mood===2?'今日はゆっくり。そばにいるよ。':welcomeText(welcome,hour);
 const room=rooms.find(r=>r.id===settings.room)??rooms[0],nextRoom=rooms.find(r=>r.cost>state.stars);
 function prepareEntry(e:Entry,recordWeight=false){const candidate=weightDraft(stateRef.current.entries,e,recordWeight);setDraft({...e,done:[...e.done]});setWeight(candidate.value);setWeightIncluded(candidate.included);setWalkingMinutes(String(e.walkingMinutes??0));setWalkingIncluded(e.walkingMinutes!=null)}
 function openEntry(e:Entry=entry,recordWeight=false){prepareEntry(e,recordWeight);setRecordMode(recordWeight?'weight':'daily');setEntryOpen(true)}
 function openWalking(e:Entry=entry){prepareEntry(e);setWalkingIncluded(true);setRecordMode('walking');setEntryOpen(true)}
 function openNote(e:Entry=entry){prepareEntry(e);setRecordMode('note');setEntryOpen(true)}
 async function submitEntry(ev:React.FormEvent){
 ev.preventDefault();
 const num=weightIncluded?(weight.trim()===''?NaN:Number(weight)):null;
 const minutes=walkingIncluded?(walkingMinutes.trim()===''?NaN:Number(walkingMinutes)):null;
 if(!walkingOnly&&!noteOnly&&num!==null&&(!Number.isFinite(num)||num<1||num>500)){toast.error('体重は1〜500kgの範囲で入力してください。');return}
 if(!weightOnly&&!noteOnly&&minutes!==null&&(!Number.isInteger(minutes)||minutes<0||minutes>1440)){toast.error('ウォーキング時間は0〜1440分の整数で入力してください。');return}
 const savedEntry=stateRef.current.entries.find(e=>e.day===draft.day)??blank(draft.day);
 const next=noteOnly?{...savedEntry,note:draft.note??''}:weightOnly?{...savedEntry,weight:num}:walkingOnly?{...savedEntry,walkingMinutes:minutes}:{...draft,weight:num,walkingMinutes:minutes};
 if(await save({kind:'entry',...next}))setEntryOpen(false)
 }
 function changeDate(day:string){const e=state.entries.find(e=>e.day===day)??blank(day);prepareEntry(e,weightIncluded)}
 function saveCare(patch:CareDay){return save({kind:'care',day:currentDay,...patch},true)}
 function openGoal(){setGoalDraft(stateRef.current.settings.goal);setWeeklyDraft(stateRef.current.settings.weeklyDays);setGoalOpen(true)}
 function openSettings(){setEditSettings({...settings,habits:[...settings.habits]});setSettingsOpen(true)}
 if(!signedIn)return <div className="login-wrap"><header className="brand"><span className="brand-mark"><PawPrint/></span>もちと、まいにち</header><main className="login-card"><div className="eyebrow">MY LITTLE COMPANION</div><Pet/><h1>きょうの小さな「できた」を、<br/>いっしょに。</h1><p>体重も、気分も、毎日の習慣も。<br/>あなたのペースを、もちが応援します。</p><Button className="login-button" asChild><a href={signInPath} target="_top"><LockKeyhole size={18}/>ChatGPTでログイン</a></Button><p className="privacy"><LockKeyhole size={14}/>招待された方だけの、プライベートな記録</p></main><a className="install-link" href={base+'install'}>ホーム画面への追加・使い方</a><footer className="login-footer">おやすみの日があっても、いつでもおかえり。</footer></div>;
 if(signedIn&&!loading&&loaded&&!settings.onboardingComplete)return <div className="onboarding"><Toaster position="top-center" theme="light"/><header className="brand"><span className="brand-mark"><PawPrint/></span>もちと、まいにち</header><main><p className="eyebrow">はじめまして、これからよろしくね</p><h1>まいにちを、一緒に過ごす相棒。</h1><p className="onboarding-copy">気になる子と、これからのゆるい目標を選んでね。<br/>名前も目標も、あとから変えられます。</p>{safariTab&&<p className="device-hint">ホーム画面から使うなら、先にホーム画面に追加してから始めてね。Safariとホーム画面のもちでは、記録が別々に保存されます。<a href={base+'install'}>追加のしかた</a></p>}{error&&<p className="error-banner" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();await save({kind:'settings',...settings,species:chosenSpecies,name:chosenName.trim(),goal:chosenGoal.trim(),onboardingComplete:true},true)}}><PetPicker value={chosenSpecies} onChange={setChosenSpecies} disabled={saving}/><div className="onboarding-name"><label className="field-label" htmlFor="first-pet-name">相棒の名前</label><Input id="first-pet-name" value={chosenName} required maxLength={12} onChange={e=>setChosenName(e.target.value)} disabled={saving}/><GoalPicker value={chosenGoal} onChange={setChosenGoal} disabled={saving}/><Button className="save-button" disabled={saving||!chosenName.trim()}>{saving?<LoaderCircle className="spin"/>:<PawPrint size={19}/>}この子とはじめる</Button></div></form><p className="kind-note">がんばる日も、おやすみの日も。いつも味方だよ。</p></main></div>;
 return <div className="app-shell"><Toaster position="top-center" theme="light"/><header className="topbar"><a href={base} className="brand"><span className="brand-mark"><PawPrint/></span><span>もちと、まいにち<small>MY LITTLE COMPANION</small></span></a><div className="header-right"><span className="private-tag"><LockKeyhole size={13}/>あなただけの記録</span><Button variant="ghost" size="icon" className="settings-button" aria-label="設定を開く" onClick={openSettings} disabled={loading||!loaded||saving||failedBody!==null}><SettingsIcon size={20}/></Button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="app-tabs"><TabsList className="main-nav" aria-label="メインメニュー"><TabsTrigger value="today"><House/>きょう</TabsTrigger><TabsTrigger value="history"><ChartNoAxesCombined/>ふりかえり</TabsTrigger><TabsTrigger value="rewards"><Gift/>ごほうび</TabsTrigger></TabsList>
 <main className="main-content"><div className="page-heading"><div><p className="date-line">{new Date(currentDay+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Tokyo'})}</p><h1>{tab==='today'?'きょうも、自分のペースで。':tab==='history'?'少しずつ、つづいてる。':'小さなできたが、たからもの。'}</h1></div><div className="star-total"><Star size={19} fill="currentColor"/><strong>{state.stars}</strong><span>おほしさま</span></div></div>
 {offline&&!onDevice&&<p className="connection-banner" role="status">いまはオフラインです。記録の保存には接続が必要です。</p>}{saving&&<p className="save-status" role="status"><LoaderCircle className="spin" size={16}/>保存を確認しています…</p>}{error&&<div className="error-banner" role="alert"><span>{error}</span>{!loading&&(failedBody!==null?<div className="retry-actions"><Button variant="outline" disabled={saving} onClick={()=>void save(failedBody)}>前の操作をもう一度保存</Button><small>未送信の入力はこの画面に残っています。閉じる前に保存してください。</small></div>:<Button variant="outline" onClick={load}>再読み込み</Button>)}</div>}
 {loading?<div className="loading-grid" aria-label="記録を読み込み中"><Skeleton className="h-96 rounded-3xl"/><Skeleton className="h-96 rounded-3xl"/></div>:<>
 <TabsContent value="today"><div className="today-grid"><section className="companion-card" style={{backgroundColor:room.color}}><div className="companion-top"><span className="small-label"><Heart size={15}/>{settings.name}のお部屋</span><span className="room-label">{room.name}</span></div><div className="companion-goal"><div className="section-heading"><span className="small-label"><Target size={16}/>わたしの目標</span><Button type="button" variant="ghost" size="sm" onClick={openGoal} disabled={saving||!!error||!loaded} aria-label={settings.goal?'目標を変更する':'目標を選ぶ'}><Pencil size={14}/>{settings.goal?'変更':'選ぶ'}</Button></div><p>{settings.goal||'これからの、ゆるい目標を選んでみよう。'}</p></div><PetPlayground species={settings.species} outfit={settings.outfit} name={settings.name} pose={care.finished?2:pose} message={message} resting={care.resting} quiet={care.quiet} onInteract={()=>setDemoPose(null)} onLounge={()=>setLoungeOpen(true)}/><details className="expression-details"><summary>表情を見てみる</summary><div className="expression-buttons" aria-label="相棒の表情を見てみる">{(settings.outfit==='none'?[4,5,6,2]:settings.outfit==='starlight'?[0,3,2,6]:[0,1]).map(n=><button key={n} type="button" aria-pressed={demoPose===n} onClick={()=>setDemoPose(n)}>{expressionLabel(n)}</button>)}</div></details><div className="companion-counts"><div className="together"><PawPrint size={18}/><span>会いに来た日</span><strong>{visits.length}<small>日</small></strong></div><div className="together record-together"><span>いっしょに記録した日</span><strong>{allDays}<small>日</small></strong></div></div></section>
 <div className="daily-panels"><section className="card daily-care-card"><div className="section-heading"><h2>きょうの過ごし方</h2><span className="subtle">毎日、選び直せるよ</span></div><div className="care-mode-buttons"><Button type="button" variant={care.light?'secondary':'outline'} aria-pressed={care.light} disabled={saving||!!error} onClick={()=>void saveCare({light:!care.light})}><Heart size={16}/>今日は軽め</Button><Button type="button" variant={care.resting?'secondary':'outline'} aria-pressed={care.resting} disabled={saving||!!error} onClick={()=>{setShowRestRecords(false);void saveCare({resting:!care.resting,finished:false})}}><Moon size={16}/>{care.resting?'おやすみ中':'今日は休む'}</Button></div><p className="support-copy">{care.resting?'休むことも、今日の大切な過ごし方。':care.light?'今日は、ひとつだけでも花まる。':'できる日も、休む日も。自分のペースで。'}</p><details className="care-options"><summary>自分のペースを選ぶ</summary><Button type="button" variant="ghost" aria-pressed={care.quiet} disabled={saving||!!error} onClick={()=>void saveCare({quiet:!care.quiet})}>{care.quiet?'今日は見守り中・提案を戻す':'今日は提案をお休み'}</Button><Button type="button" variant="ghost" disabled={saving||!!error} onClick={()=>setSmallGoalOpen(true)}>目標を小さな一歩にする</Button><Button type="button" variant="ghost" disabled={saving||!!error} onClick={openGoal}>会うペースを選ぶ</Button></details></section>{!panelsOpen&&<section className="card rest-day-card">{care.finished?<Flower2 size={28}/>:<Moon size={25}/>}<h2>{care.finished?'今日はここまでで、花まる。':'今日は、一緒におやすみ。'}</h2><p>{care.finished?'残した記録も、もちとの時間も、ここにあるよ。ゆっくり過ごしてね。':'休む時間も、あしあとに残るよ。もちも元気に、のんびり過ごしているよ。'}</p><Button type="button" variant="outline" onClick={()=>setLoungeOpen(true)}>もちと、ひと休み</Button><Button type="button" variant="ghost" disabled={saving||!!error} onClick={()=>{setShowRestRecords(true);if(care.finished)void saveCare({finished:false})}}>記録を開く</Button></section>}{panelsOpen&&<><section className="card mood-card"><div className="section-heading"><h2>いま、どんな気分？</h2><span className="subtle">ひとつ選んでね</span></div><RadioGroup className="mood-options" value={entry.mood===null?'':String(entry.mood)} onValueChange={v=>void save({kind:'entry',...entry,mood:Number(v)},true)} disabled={saving||!!error||!loaded}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(entry.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={31}/><span>{moodNames[i]}</span>{entry.mood===i&&<Check size={13} className="mood-check"/>}</label>)}</RadioGroup></section>
 <section className={"card habits-card "+(care.light&&!moreHabits?"light-habits":"")}><div className="section-heading"><h2>きょうの小さな習慣</h2></div><p className="support-copy">ひとつできたら、それだけで花まる。</p><div className="habit-list">{settings.habits.map((habit,i)=>{const Icon=[Footprints,StretchHorizontal,Utensils][i],checked=entry.done.includes('h'+i);if(care.light&&!moreHabits&&i!==0)return null;return <label className={'habit '+(checked?'completed':'')} key={i}><span className={'habit-icon habit-'+i}><Icon size={21}/></span><span>{habit}</span><Checkbox aria-label={habit} checked={checked} disabled={saving||!!error||!loaded} onCheckedChange={v=>void save({kind:'entry',...entry,done:v?[...entry.done,'h'+i]:entry.done.filter(h=>h!=='h'+i)},true)} className="habit-check"/></label>})}</div>{care.light&&settings.habits.length>1&&<button type="button" className="more-habits" aria-expanded={moreHabits} onClick={()=>setMoreHabits(!moreHabits)}>{moreHabits?'ひとつだけに戻す':'ほかの習慣も見る'}</button>}<div className="habit-summary gentle-habit-summary"><span>{entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length?entry.done.filter(h=>Number(h.slice(1))<settings.habits.length).length+'つの小さな「できた」':'できる日に、ひとつずつ。'}</span></div></section>
 {settings.showWeight&&<section className="card weight-card"><div className="weight-icon"><Scale size={22}/></div><div className="weight-card-copy"><h2>{entry.weight!==null||!weightRecord?'きょうの体重':'前回の体重'} <span className="optional">任意</span></h2><p className="weight-value">{weightRecord?.weight?.toFixed(1)??'—'}<span>kg</span></p>{weightRecord&&<><WeightDifference record={weightRecord} entries={state.entries}/>{entry.weight===null&&<small className="weight-carried">{weightDate(weightRecord.day)}の記録 · 今日はまだ未記録</small>}</>}</div><Button variant="outline" onClick={()=>openEntry(entry,true)} disabled={saving||!!error||!loaded}>{entry.weight===null?<Plus size={16}/>:<Pencil size={16}/>} {entry.weight===null?'記録する':'編集する'}</Button></section>}
 <section className="card weight-card walking-card"><div className="weight-icon walking-icon"><Footprints size={22}/></div><div className="weight-card-copy"><h2>ウォーキング時間 <span className="optional">任意</span></h2><p className="weight-value">{entry.walkingMinutes??'—'}<span>分</span></p><small className="weight-carried">{entry.walkingMinutes==null?'今日はまだ未記録':'今日歩いた時間'}</small></div><Button variant="outline" aria-label={entry.walkingMinutes==null?'ウォーキング時間を記録する':'ウォーキング時間を編集する'} onClick={()=>openWalking()} disabled={saving||!!error||!loaded}>{entry.walkingMinutes==null?<Plus size={16}/>:<Pencil size={16}/>} {entry.walkingMinutes==null?'記録する':'編集する'}</Button></section>
 </>}</div></div>{panelsOpen&&<section className="card daily-note"><div className="section-heading"><h2>きょうのひとこと</h2><Button variant="outline" disabled={saving||!!error||!loaded} onClick={()=>openNote()}>メモを書く</Button></div><p className={entry.note?'note-text':'support-copy'}>{entry.note||'食べたもの、今日よかったこと。なんでも残してね。'}</p><WaitingPet species={settings.species} outfit={settings.outfit} saved={celebrate}/></section>}{!care.finished&&<section className="today-ending"><p>{entry.done.length?'ひとつできたら、それだけで花まる。':'会えた時間も、今日の小さなあしあと。'}</p><Button type="button" variant="outline" disabled={saving||!!error} onClick={()=>void saveCare({finished:true})}><Check size={16}/>今日はここまで</Button></section>}<section className="week-strip"><div><h2>今週のあしあと</h2><p>{settings.weeklyDays?`会えた日 ${weeklyVisits}日 · 週に${settings.weeklyDays}日くらいのペース`:'会える日に、ゆっくり。'}</p><p>{weekEntries.length?`${weekEntries.length}日、自分を気にかけたね。`:'休む日も、余白の日も、大切に。'}</p></div><CareCalendar entries={state.entries} days={week} today={currentDay}/><p className="calendar-key"><PawPrint size={13}/>記録 <Moon size={13}/>おやすみ <span className="visit-dot"/>会えた日</p></section><p className="kind-note"><Heart size={14}/>がんばる日も、おやすみの日も。{settings.name}と一緒に。</p></TabsContent>
 <TabsContent value="history"><HistoryView entries={state.entries} day={currentDay} onEdit={openEntry} onWeight={()=>openEntry(entry,true)} onWalking={()=>openWalking()} onNote={openNote}/></TabsContent>
 <TabsContent value="rewards"><section className="reward-intro"><div className="reward-star"><Star fill="currentColor" size={32}/></div><div><h2>集めたおほしさま <strong>{state.stars}<small>こ</small></strong></h2><p>気分・体重・習慣の記録で、それぞれ1日1こ。<br/>一度集めたおほしさまは、減りません。</p></div></section>{nextRoom&&<div className="next-reward"><span>次のお部屋まで、あと <b>{nextRoom.cost-state.stars}こ</b></span><Progress value={state.stars/nextRoom.cost*100}/></div>}<h2 className="reward-section-title">お部屋</h2><div className="rooms-grid">{rooms.map((r,i)=>{const unlocked=state.stars>=r.cost,selected=settings.room===r.id;return <section className={'room-card '+(selected?'chosen':'')} key={r.id}><div className="room-preview" style={{backgroundColor:r.color}}><Pet species={settings.species} small pose={i} outfit={settings.outfit}/>{!unlocked&&<span className="room-lock"><LockKeyhole size={18}/>{r.cost}こでひらく</span>}</div><div className="room-details"><h3>{r.name}</h3><Button variant={selected?'secondary':'outline'} disabled={!unlocked||selected||saving||!!error} onClick={()=>void save({kind:'settings',...settings,room:r.id})}>{selected?<><Check size={15}/>使用中</>:unlocked?'このお部屋にする':<><Star size={15}/>{r.cost}こ</>}</Button></div></section>})}</div><RewardGallery settings={settings} stars={state.stars} disabled={saving||!!error||!loaded} onEquip={async outfit=>{if(await save({kind:'settings',...settings,outfit},true)){setCelebrate(true);toast.success('衣装に着替えたよ')}}} onMeet={async()=>{if(settings.outfit==='starlight'||await save({kind:'settings',...settings,outfit:'starlight'},true)){setTab('today');window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setCelebrate(true);toast.success('特別なもちに会えたよ')}}}/><p className="kind-note"><Heart size={14}/>おほしさまは、体重の増減ではなく「できた」のしるし。</p></TabsContent>
 </>}
 </main></Tabs>
 <Dialog open={loungeOpen} onOpenChange={setLoungeOpen}><DialogContent className="app-dialog lounge-dialog" style={{backgroundColor:room.color}}><DialogTitle>もちと、ひと休み</DialogTitle><DialogDescription>何もしない時間も、一緒に。いつでも閉じられるよ。</DialogDescription><PetPlayground species={settings.species} outfit={settings.outfit} name={settings.name} pose={2} message="ここで、のんびり一緒に過ごそう。" resting quiet compact/></DialogContent></Dialog>
 <Dialog open={smallGoalOpen} onOpenChange={setSmallGoalOpen}><DialogContent className="app-dialog"><DialogTitle>もっと小さな、一歩へ</DialogTitle><DialogDescription>今の自分に合う目標へ、いつでも選び直せるよ。</DialogDescription>{settings.goal&&<p className="support-copy">今の目標：{settings.goal}</p>}<div className="smaller-goals">{smallerGoals(settings.goal).map(goal=><Button type="button" variant="outline" key={goal} disabled={saving} onClick={async()=>{if(await save({kind:'settings',...stateRef.current.settings,goal},true))setSmallGoalOpen(false)}}>{goal}</Button>)}</div><Button type="button" variant="ghost" onClick={()=>setSmallGoalOpen(false)}>今の目標のままで大丈夫</Button></DialogContent></Dialog>
 <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogContent className="app-dialog goal-dialog"><DialogTitle>これからの、ゆるい目標</DialogTitle><DialogDescription>途中で変えても、おやすみしても大丈夫。</DialogDescription><form onSubmit={async event=>{event.preventDefault();if(await save({kind:'settings',...stateRef.current.settings,goal:goalDraft.trim(),weeklyDays:weeklyDraft}))setGoalOpen(false)}}>{goalOpen&&<GoalPicker value={goalDraft} onChange={setGoalDraft} disabled={saving}/>}<WeeklyPace value={weeklyDraft} onChange={setWeeklyDraft} disabled={saving}/><Button className="save-button" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>}目標を保存する</Button></form></DialogContent></Dialog>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="app-dialog"><DialogTitle>あなたと、相棒のこと</DialogTitle><DialogDescription>心地よく続けられる形にしよう。</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await save({kind:'settings',...editSettings}))setSettingsOpen(false)}}>{settingsOpen&&<GoalPicker value={editSettings.goal} onChange={goal=>setEditSettings({...editSettings,goal})} disabled={saving}/>}<WeeklyPace value={editSettings.weeklyDays} onChange={weeklyDays=>setEditSettings({...editSettings,weeklyDays})} disabled={saving}/><div className="field-label">相棒の種類</div><PetPicker value={editSettings.species} onChange={species=>setEditSettings({...editSettings,species})} disabled={saving}/><p className="support-copy">相棒を変えても、記録・おほしさま・衣装はそのまま。</p><label className="field-label" htmlFor="pet-name">相棒の名前</label><Input id="pet-name" value={editSettings.name} maxLength={12} required onChange={e=>setEditSettings({...editSettings,name:e.target.value})}/><div className="field-label">毎日の習慣 <span className="subtle">最大3つ</span></div><p className="subtle">無理なくできそうなことを選んでね。</p><div className="habit-edit">{editSettings.habits.map((h,i)=><div className="habit-edit-row" key={i}><Input aria-label={`習慣${i+1}`} value={h} maxLength={30} required onChange={e=>setEditSettings({...editSettings,habits:editSettings.habits.map((v,j)=>i===j?e.target.value:v)})}/><select aria-label={`習慣${i+1}の候補`} value="" onChange={e=>{const choice=e.target.value;if(choice)setEditSettings({...editSettings,habits:editSettings.habits.map((v,j)=>i===j?choice:v)})}}><option value="">候補から選ぶ</option>{habitSuggestions.map(s=><option key={s} value={s}>{s}</option>)}</select></div>)}</div><div className="habit-edit-actions">{editSettings.habits.length<3&&<Button type="button" variant="outline" onClick={()=>setEditSettings({...editSettings,habits:[...editSettings.habits,'']})}><Plus size={15}/>習慣を追加</Button>}{editSettings.habits.length>1&&<Button type="button" variant="ghost" onClick={()=>setEditSettings({...editSettings,habits:editSettings.habits.slice(0,-1)})}>最後の習慣を外す</Button>}</div><label className="switch-label" htmlFor="show-weight"><span>ホームに体重を表示</span><Switch id="show-weight" checked={editSettings.showWeight} onCheckedChange={v=>setEditSettings({...editSettings,showWeight:v})}/></label><p className="subtle">日本時間で日付が切り替わります。</p><Button className="save-button" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>}保存する</Button></form><PilotTools screen={{today:'きょう',history:'ふりかえり',rewards:'ごほうび'}[tab]??tab} storage={storage}/><a className="install-link" href={base+'install'}>ホーム画面への追加・使い方</a><div className="account-footer"><LockKeyhole size={14}/><span>{onDevice?'記録はこの端末のブラウザの中にだけ保存されます。':'記録はログインした本人だけが見られます。'}</span></div>{!onDevice&&<a className="logout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/>ログアウト</a>}</DialogContent></Dialog>
 <Dialog open={entryOpen} onOpenChange={setEntryOpen}>
 <DialogContent className={'app-dialog '+(singleFieldOnly?'weight-only-dialog':'')}>
 <DialogTitle>{noteOnly?(draft.note?'メモを編集':'メモを書く'):walkingOnly?(draft.walkingMinutes!=null?'ウォーキング時間を編集':'ウォーキング時間を記録'):weightOnly?(draft.weight!==null?'体重を編集':'体重を記録'):draft.day===currentDay?'きょうの記録':draft.day.replaceAll('-',' / ')+'の記録'}</DialogTitle>
 <DialogDescription>{noteOnly?'今日よかったこと、なんでも残してね。':walkingOnly?'上下にスクロールして、歩いた分数を選んでね。':weightOnly?'上下にスクロールして、今日の体重に合わせてね。':'どれかひとつだけでも、大丈夫。'}</DialogDescription>
 <form onSubmit={submitEntry}><WaitingPet species={settings.species} outfit={settings.outfit}/>
 {singleFieldOnly?<p className="weight-record-day">{new Date(draft.day+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',timeZone:'Asia/Tokyo'})}{noteOnly?'のメモ':walkingOnly?'のウォーキング時間':'の体重'}</p>:<><label className="field-label" htmlFor="entry-day">日付</label><Input type="date" id="entry-day" required value={draft.day} min="2000-01-01" max={currentDay} onChange={e=>changeDate(e.target.value)}/></>}
 {!walkingOnly&&!noteOnly&&<WeightPicker value={weight} included={weightIncluded} previous={draftPreviousWeight} disabled={saving} optional={!weightOnly} onChange={setWeight} onIncludedChange={setWeightIncluded}/>}
 {!weightOnly&&!noteOnly&&<WalkingPicker value={walkingMinutes} included={walkingIncluded} previous={draftPreviousWalking} disabled={saving} optional={!walkingOnly} onChange={setWalkingMinutes} onIncludedChange={setWalkingIncluded}/>}
 {!singleFieldOnly&&<>
 <div className="field-label">気分</div><RadioGroup className="mood-options" value={draft.mood===null?'':String(draft.mood)} onValueChange={v=>setDraft({...draft,mood:Number(v)})}>{MoodIcons.map((Icon,i)=><label key={i} className={'mood-option '+(draft.mood===i?'selected':'')}><RadioGroupItem value={String(i)} className="sr-only"/><Icon size={26}/><span>{moodNames[i]}</span></label>)}</RadioGroup>
 <div className="field-label">できた習慣</div>{settings.habits.map((h,i)=><label className="draft-habit" key={i}><Checkbox checked={draft.done.includes('h'+i)} onCheckedChange={v=>setDraft({...draft,done:v?[...draft.done,'h'+i]:draft.done.filter(x=>x!=='h'+i)})}/>{h}</label>)}
 </>}
 {(!singleFieldOnly||noteOnly)&&<><label className="field-label" htmlFor="daily-note">自由メモ <span className="subtle">任意・2000文字まで</span></label><Textarea id="daily-note" value={draft.note??''} disabled={saving} maxLength={2000} rows={4} placeholder="今日よかったこと、食べたもの、明日の自分へ。" onChange={e=>setDraft({...draft,note:e.target.value})}/><p className="subtle note-count">{(draft.note??'').length} / 2000</p></>}
 {error&&<p role="alert" className="form-error">{error}<br/>入力は残っています。下のボタンから再保存できます。</p>}
 <Button className="save-button" disabled={saving||!draft.day}>{saving?<LoaderCircle className="spin"/>:<Check size={18}/>} {noteOnly?'メモを保存する':walkingOnly?'ウォーキング時間を保存する':weightOnly?'体重を保存する':'記録を保存する'}</Button>
 </form>
 </DialogContent></Dialog>
 </div>
}
