'use client';
import { useRef, useState } from 'react';
import { Check, LockKeyhole, Sparkles, Star, Shirt, Home, Heart, Gift, ChevronRight, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { regularOutfits, outfits, rooms, pets, allRewardsCost, allRewardsUnlocked, type Settings, type Outfit, type Species } from '@/lib/mochi';
import type { CompanionState } from '@/lib/companion';
import { outfitStory } from '@/lib/companion-content';
import { Pet } from './pet';
import { RewardDelivery } from './reward-delivery';
import { CollectionPager, slicePage } from './collection-pager';

const groups=['いつものおめかし','お花とくだもの','まいにちのおしごと','夢とお祝い'];
export function RewardGallery({settings,stars,disabled,onEquip,onRoom,onMeet,companion,onPreview,onWishlist,onReceive}:{settings:Settings;stars:number;disabled:boolean;onEquip:(outfit:Outfit)=>Promise<boolean>;onRoom:(room:string)=>Promise<boolean>;onMeet:()=>void;companion:CompanionState;onPreview:(outfit:Outfit)=>void;onWishlist:(outfit:Outfit|null)=>void;onReceive:(outfit:Outfit)=>Promise<boolean>}){
 const [view,setView]=useState('outfits'),[group,setGroup]=useState('all'),[onlyUnlocked,setOnlyUnlocked]=useState(false),[page,setPage]=useState(0),[species,setSpecies]=useState<Species>(settings.species),[detail,setDetail]=useState<Outfit|null>(null),[compare,setCompare]=useState(false),[delivery,setDelivery]=useState(false);
 const outfitList=useRef<HTMLDivElement>(null);
 const unlockedCount=regularOutfits.filter(item=>item.cost<=stars).length,completed=unlockedCount+rooms.filter(item=>item.cost<=stars).length,total=regularOutfits.length+rooms.length,allUnlocked=allRewardsUnlocked(stars);
 const waiting=outfits.filter(item=>companion.receipts[item.id]&&!companion.receipts[item.id].seen);
 const visible=regularOutfits.filter((item,index)=>(group==='all'||Math.floor(index/8)===Number(group))&&(!onlyUnlocked||stars>=item.cost)),current=slicePage(visible,page,4);
 const item=regularOutfits.find(item=>item.id===detail),wish=regularOutfits.find(item=>item.id===companion.preferences.wishlist),next=wish??regularOutfits.find(item=>item.cost>stars),nextRoom=rooms.find(item=>item.cost>stars);
 const unlocked=item?stars>=item.cost:false,selected=item?settings.outfit===item.id:false;
 function open(outfit:Outfit){setDetail(outfit);setCompare(false)}
 function changePage(next:number){setPage(next);outfitList.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
 return <div className="reward-browser collection-browser">
  <div className="collection-progress"><span><Shirt size={20}/><strong>{unlockedCount}<small> / 32</small></strong><small>衣装を解放</small></span>{waiting.length>0&&<Button type="button" variant="outline" className="new-reward-package" onClick={()=>setDelivery(true)}><Gift size={17}/>包み {waiting.length}</Button>}</div>
  <Tabs value={view} onValueChange={setView}><TabsList className="collection-tabs reward-sections" aria-label="ごほうびの種類"><TabsTrigger value="outfits"><Shirt size={20}/>おめかし</TabsTrigger><TabsTrigger value="rooms"><Home size={20}/>お部屋</TabsTrigger><TabsTrigger value="special"><Sparkles size={20}/><span>特別なもち</span></TabsTrigger></TabsList>
   <TabsContent value="outfits"><div className="closet-toolbar"><select aria-label="衣装の種類" value={group} onChange={event=>{setGroup(event.target.value);setPage(0)}}><option value="all">すべての衣装 · 32</option>{groups.map((label,index)=><option key={label} value={index}>{label} · 8</option>)}</select><Button type="button" variant={onlyUnlocked?'secondary':'outline'} aria-pressed={onlyUnlocked} onClick={()=>{setOnlyUnlocked(!onlyUnlocked);setPage(0)}}><Check size={14}/>解放済み</Button></div><div className="closet-species" aria-label="衣装のイラストを見る相棒">{pets.map(pet=><button type="button" key={pet.id} aria-pressed={species===pet.id} onClick={()=>setSpecies(pet.id)}>{pet.name}{pet.id===settings.species&&<span>いまの子</span>}</button>)}</div>
    {current.items.length?<><div ref={outfitList} className="compact-outfit-grid">{current.items.map(outfit=>{const unlocked=stars>=outfit.cost,wearing=settings.outfit===outfit.id;return <button type="button" className={'reward-tile '+(wearing?'wearing':'')} key={outfit.id} aria-label={outfit.name+'の詳細を見る'} onClick={()=>open(outfit.id)}><div className="reward-tile-picture"><Pet species={species} outfit={outfit.id} pose={wearing?1:0}/>{companion.preferences.wishlist===outfit.id&&<Heart size={15} fill="currentColor" className="wish-pin"/>}</div><strong>{outfit.name}</strong><span className={'reward-tile-state '+(unlocked?'available':'')}>{wearing?<><Check size={12}/>着用中</>:unlocked?<><Check size={12}/>解放済み</>:<><LockKeyhole size={12}/>{outfit.cost}こ</>}</span></button>})}</div><CollectionPager {...current} label="衣装" onChange={changePage}/></>:<div className="collection-empty"><Shirt size={34}/><p>この種類の衣装は、これから</p><Button type="button" variant="outline" onClick={()=>{setOnlyUnlocked(false);setGroup('all');setPage(0)}}>すべての衣装を見る</Button></div>}
    <div className="closet-bottom-actions"><Button type="button" variant="ghost" disabled={disabled||settings.outfit==='none'} onClick={()=>void onEquip('none')}><ArrowLeft size={15}/>いつものすがた</Button>{next&&<button type="button" className="next-keepsake" onClick={()=>open(next.id)}>{wish?<Heart size={15}/>:<Star size={15}/>}<span>{wish?'会いたい衣装':'次のおめかし'}<strong>{next.name}</strong></span><b>{stars>=next.cost?'解放済み':`あと${next.cost-stars}こ`}</b><ChevronRight size={15}/></button>}</div>
   </TabsContent>
   <TabsContent value="rooms"><div className="room-collection-title"><h2>お部屋を選ぶ</h2><span>{rooms.filter(item=>item.cost<=stars).length} / {rooms.length} 解放</span></div>{nextRoom&&<p className="next-room-short">次のお部屋まで、あと <strong>{nextRoom.cost-stars}こ</strong></p>}<div className="compact-room-grid">{rooms.map((room,index)=>{const unlocked=stars>=room.cost,selected=settings.room===room.id;return <section className={'room-card '+(selected?'chosen':'')} key={room.id}><div className="room-preview" style={{backgroundColor:room.color}}><Pet species={settings.species} pose={index} outfit={settings.outfit}/>{!unlocked&&<span className="room-lock"><LockKeyhole size={13}/>{room.cost}こ</span>}</div><div className="room-details"><h3>{room.name}</h3><Button type="button" variant={selected?'secondary':'outline'} disabled={!unlocked||selected||disabled} onClick={()=>void onRoom(room.id)}>{selected?<><Check size={14}/>使用中</>:unlocked?'このお部屋にする':<><Star size={14}/>あと{room.cost-stars}こ</>}</Button></div></section>})}</div></TabsContent>
   <TabsContent value="special"><section className={'special-reward compact-special '+(allUnlocked?'unlocked':'')} aria-label="全解放の特別なもち"><div className="section-heading"><span className="small-label"><Sparkles size={17}/>すべてひらいた、その先に</span><span className="subtle">{completed} / {total}</span></div><h2>{allUnlocked?'ほしぞらの特別なもち':'特別なもちが、待っているよ'}</h2>{allUnlocked?<><div className="special-pets">{pets.map(pet=><figure key={pet.id}><Pet species={pet.id} outfit="starlight" pose={1} small/><figcaption>{pet.name}</figcaption></figure>)}</div><Button type="button" className="special-meet-button" disabled={disabled} onClick={onMeet}><Sparkles size={18}/>特別なもちに会う</Button></>:<><div className="special-mystery" aria-hidden="true"><Sparkles size={48}/><LockKeyhole size={22}/></div><p>32種類の衣装と、4つのお部屋をひらくと会えるよ。</p><Progress value={Math.min(100,stars/allRewardsCost*100)} aria-label="全ごほうびの解放まで"/><span className="special-remaining">あと {Math.max(0,allRewardsCost-stars)}こで、すべて解放</span></>}</section></TabsContent>
  </Tabs>
  <Dialog open={!!item} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="app-dialog collection-detail outfit-reader"><DialogTitle>{item?.name}</DialogTitle><DialogDescription className="sr-only">衣装のイラストと試着・着替え</DialogDescription>{item&&<><div className="collection-detail-body"><div className="outfit-detail-picture">{compare?<div className="outfit-comparison">{pets.map(pet=><figure key={pet.id}><Pet species={pet.id} outfit={item.id} pose={0}/><figcaption>{pet.name}</figcaption></figure>)}</div>:<Pet species={species} outfit={item.id} pose={selected?1:0}/>}</div><div className="outfit-detail-tools"><Button type="button" variant="ghost" onClick={()=>setCompare(!compare)}>{compare?'1匹で見る':'3匹を見比べる'}</Button><Button type="button" variant={companion.preferences.wishlist===item.id?'secondary':'outline'} disabled={disabled} aria-pressed={companion.preferences.wishlist===item.id} onClick={()=>onWishlist(companion.preferences.wishlist===item.id?null:item.id)}><Heart size={16} fill={companion.preferences.wishlist===item.id?'currentColor':'none'}/>{companion.preferences.wishlist===item.id?'会いたい衣装':'会いたい'}</Button></div><p className="outfit-detail-note">{item.note}</p><span className="outfit-unlock-status">{selected?<><Check size={16}/>{settings.name}が着用中</>:unlocked?<><Check size={16}/>解放済み</>:<><Star size={16}/>あと {item.cost-stars}こ</>}</span><details className="hub-secondary"><summary>このおめかしのお話</summary><p>{outfitStory(item.id,item.name,item.note)}</p>{companion.receipts[item.id]&&<p className="receipt-origin">{companion.receipts[item.id].day.replaceAll('-',' / ')} · {companion.receipts[item.id].source}</p>}</details></div><div className="collection-detail-footer outfit-actions"><Button type="button" variant="outline" onClick={()=>{setDetail(null);onPreview(item.id)}}>{settings.name}で試着する</Button><Button type="button" disabled={disabled||!unlocked||selected} onClick={async()=>{if(await onEquip(item.id))setDetail(null)}}>{selected?'着用中':unlocked?`${settings.name}に着せる`:`あと${item.cost-stars}こ`}</Button></div></>}</DialogContent></Dialog>
  <Dialog open={delivery} onOpenChange={setDelivery}><DialogContent className="app-dialog collection-detail package-reader"><DialogTitle><Gift size={20}/>もちからの衣装</DialogTitle><DialogDescription className="sr-only">届いた衣装の包みをひらく</DialogDescription><div className="collection-detail-body"><RewardDelivery companion={companion} species={settings.species} disabled={disabled} onPreview={id=>{setDelivery(false);onPreview(id)}} onReceive={async id=>{const ok=await onReceive(id);if(ok&&waiting.length===1)setDelivery(false);return ok}}/></div></DialogContent></Dialog>
 </div>;
}
